#include "ft_printf.h"
#include <stdio.h>

int	main(void)
{

	printf("NO SPEC OR DOUBLE TEST\n");
	printf("%d\n", printf("[decimal %dd]\n", 42));
	printf("%d\n", ft_printf("[decimal %dd]\n", 42));
	printf("-------\n");
	printf("%d\n", printf("[decimal %idii]\n", 42));
	printf("%d\n", ft_printf("[decimal %idii]\n", 42));
	printf("-------\n");
	printf("%d\n", printf("[decimal %uuip]\n", 4200000));
	printf("%d\n", ft_printf("[decimal %uuip]\n", 4200000));
	printf("-------\n");
	printf("%d\n", printf("[decimal %xXxxXX]\n", 4200000));
	printf("%d\n", ft_printf("[decimal %xXxxXX]\n", 4200000));
	printf("-------\n");
	printf("%d\n", printf("[string %sssssss]\n", "hi"));
	printf("%d\n", ft_printf("[string %sssssss]\n", "hi"));
	printf("-------\n");
	printf("%d\n", printf("[string cc%cc]\n", 'x'));
	printf("%d\n", ft_printf("[string cc%cc]\n", 'x'));
	printf("-------\n");
	printf("%d\n", printf("[string pp%40.1pp]\n", NULL));
	printf("%d\n", ft_printf("[string pp%40.1pp]\n", NULL));
	printf("-------\n");
	printf("%d\n", ft_printf("[%w]\n"));
	printf("-------\n");
	printf("%d\n", ft_printf("[%7w]\n"));
	printf("-------\n");
	printf("%d\n", ft_printf("[%07w]\n"));
	printf("-------\n");
	printf("%d\n", ft_printf("[%074]\n"));
	printf("-------\n");
	printf("%d\n", ft_printf("[%074.03]\n"));
	printf("-------\n");
	printf("%d\n", ft_printf("[%074waaa]\n"));
	printf("-------\n");
	printf("%d\n", ft_printf("[%-7w]\n"));
	printf("-------\n");
	printf("%d\n", ft_printf("[%0-7w]\n"));
	printf("-------\n");
	printf("%d\n", ft_printf("[aaa%0-*.*waaa]\n", -7, -9));
	printf("-------\n");
	printf("%d\n", ft_printf("[%whaaat07.9wno spec]\n"));
	printf("-------\n");
	printf("%d\n", ft_printf("[%08.-9waa]\n"));
	printf("-------\n");
	printf("%d\n", ft_printf("[%08.-0waa]\n"));
	printf("-------\n");
	printf("%d\n", ft_printf("[%error08.8waa]\n"));
	printf("-------\n");

	printf("%% TEST\n");
	printf("%d\n", printf("[%%]\n"));
	printf("%d\n", ft_printf("[%%]\n"));
	printf("-------\n");
	printf("%d\n", printf("[%.6%]\n"));
	printf("%d\n", ft_printf("[%.6%]\n"));
	printf("-------\n");
	printf("%d\n", printf("[%0.6%]\n"));
	printf("%d\n", ft_printf("[%0.6%]\n"));
	printf("-------\n");
	printf("%d\n", printf("[%03.6%]\n"));
	printf("%d\n", ft_printf("[%03.6%]\n"));
	printf("-------\n");
	printf("%d\n", printf("[%3.6%]\n"));
	printf("%d\n", ft_printf("[%3.6%]\n"));
	printf("-------\n");
	printf("%d\n", printf("[%0.-6%]\n"));
	printf("%d\n", ft_printf("[%0.-6%]\n"));
	printf("-------\n");
	printf("%d\n", printf("[%08.-6%]\n"));
	printf("%d\n", ft_printf("[%08.-6%]\n"));
	printf("-------\n");
	printf("%d\n", printf("[%.-1%]\n"));
	printf("%d\n", ft_printf("[%.-1%]\n"));
	printf("-------\n");
	printf("%d\n", printf("[%010.*%]\n", -4));
	printf("%d\n", ft_printf("[%010.*%]\n", -4));
	printf("-------\n");
	printf("%d\n", printf("[%-010.*%]\n", -4));
	printf("%d\n", ft_printf("[%-010.*%]\n", -4));
	printf("-------\n");
	printf("%d\n", printf("[%-0-10.*%]\n", -4));
	printf("%d\n", ft_printf("[%-0-10.*%]\n", -4));
	printf("-------\n");
	printf("%d\n", printf("[%.%]\n"));
	printf("%d\n", ft_printf("[%.%]\n"));
	printf("-------\n");
	printf("%d\n", printf("[%.0%]\n"));
	printf("%d\n", ft_printf("[%.0%]\n"));
	printf("-------\n");
	printf("%d\n", printf("[%.-0%]\n"));
	printf("%d\n", ft_printf("[%.-0%]\n"));
	printf("-------\n");
	printf("%d\n", printf("[%.*%]\n", -4));
	printf("%d\n", ft_printf("[%.*%]\n", -4));
	printf("-------\n");
	printf("%d\n", printf("[%.*%]\n", 21));
	printf("%d\n", ft_printf("[%.*%]\n", 21));
	printf("-------\n");
	printf("%d\n", printf("[%7%]\n"));
	printf("%d\n", ft_printf("[%7%]\n"));
	printf("-------\n");
	printf("%d\n", printf("[%--07%]\n"));
	printf("%d\n", ft_printf("[%--07%]\n"));
	printf("-------\n");
	printf("%d\n", printf("[%07.%]\n"));
	printf("%d\n", ft_printf("[%07.%]\n"));
	printf("       \n");

	printf("DI TEST\n");
	printf("%d\n", printf("[%9.7d]\n", 23));
	printf("%d\n", ft_printf("[%9.7d]\n", 23));
	printf("-------\n");
	printf("%d\n", printf("[%09.7d]\n", 21));
	printf("%d\n", ft_printf("[%09.7d]\n", 21));
	printf("-------\n");
	printf("%d\n", printf("[%7.9d]\n", 21));
	printf("%d\n", ft_printf("[%7.9d]\n", 21));
	printf("-------\n");
	printf("%d\n", printf("[%07.9d]\n", -56));
	printf("%d\n", ft_printf("[%07.9d]\n", -56));
	printf("-------\n");
	printf("%d\n", printf("[%-7.9d]\n", 3578));
	printf("%d\n", ft_printf("[%-7.9d]\n", 3578));
	printf("-------\n");
	printf("%d\n", printf("[%-07.9d]\n", 256));
	printf("%d\n", ft_printf("[%-07.9d]\n", 256));
	printf("-------\n");
	printf("%d\n", printf("[%02.1d]\n", 235));
	printf("%d\n", ft_printf("[%02.1d]\n", 235));
	printf("-------\n");
	printf("%d\n", printf("[%010.d]\n", -235));
	printf("%d\n", ft_printf("[%010.d]\n", -235));
	printf("-------\n");
	printf("%d\n", printf("[%010.*d]\n", -4, 235));
	printf("%d\n", ft_printf("[%010.*d]\n", -4, 235));
	printf("-------\n");
	printf("%d\n", printf("[%*.9d]\n", -7, 23));
	printf("%d\n", ft_printf("[%*.9d]\n", -7, 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.*d]\n", -9, 23));
	printf("%d\n", ft_printf("[%7.*d]\n", -9, 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.*d]\n", 0, 23));
	printf("%d\n", ft_printf("[%7.*d]\n", 0, 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.d]\n", 23));
	printf("%d\n", ft_printf("[%7.d]\n", 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.0d]\n", 23));
	printf("%d\n", ft_printf("[%7.0d]\n", 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.-0d]\n", 23));
	printf("%d\n", ft_printf("[%7.-0d]\n", 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.*d]\n", -0, 23));
	printf("%d\n", ft_printf("[%7.*d]\n", -0, 23));
	printf("-------\n");
	printf("%d\n", printf("[%07.*d]\n", -9, 0));
	printf("%d\n", ft_printf("[%07.*d]\n", -9, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*d]\n", 0, 0));
	printf("%d\n", ft_printf("[%07.*d]\n", 0, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*d]\n", -0, 0));
	printf("%d\n", ft_printf("[%07.*d]\n", -0, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.d]\n", 0));
	printf("%d\n", ft_printf("[%07.d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.0d]\n", 0));
	printf("%d\n", ft_printf("[%07.0d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.-0d]\n", 0));
	printf("%d\n", ft_printf("[%07.-0d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*d]\n", -9, 0));
	printf("%d\n", ft_printf("[%07.*d]\n", -9, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*d]\n", 0, 0));
	printf("%d\n", ft_printf("[%07.*d]\n", 0, 0));
	printf("-------\n");
	printf("%d\n", printf("[min%04.*dint]\n", 20, -2147483648));
	printf("%d\n", ft_printf("[min%04.*dint]\n", 20, -2147483648));
	printf("-------\n");
	printf("%d\n", printf("[min%04.*dint]\n", 20, -2147483650));
	printf("%d\n", ft_printf("[min%04.*dint]\n", 20, -2147483650));
	printf("-------\n");
	printf("%d\n", printf("[max%-04.*dint]\n", -20, 2147483647));
	printf("%d\n", ft_printf("[max%-04.*dint]\n", -20, 2147483647));
	printf("-------\n");
	printf("%d\n", printf("[max%-04.*dint]\n", -20, 2147483650));
	printf("%d\n", ft_printf("[max%-04.*dint]\n", -20, 2147483650));
	printf("-------\n");
	printf("%d\n", printf("[aa%04dbb]\n", -42));
	printf("%d\n", ft_printf("[aa%04dbb]\n", -42));
	printf("-------\n");
	printf("%d\n", printf("[%00-008d]\n", -21));
	printf("%d\n", ft_printf("[%00-008d]\n", -21));
	printf("-------\n");
	printf("%d\n", printf("[%007d]\n", -21));
	printf("%d\n", ft_printf("[%007d]\n", -21));
	printf("-------\n");
	printf("%d\n", printf("[%0000--8d]\n", -21));
	printf("%d\n", ft_printf("[%0000--8d]\n", -21));
	printf("-------\n");
	printf("%d\n", printf("[%---6.5d]\n", 21));
	printf("%d\n", ft_printf("[%---6.5d]\n", 21));
	printf("-------\n");
	printf("%d\n", printf("[%---6.7d]\n", -21));
	printf("%d\n", ft_printf("[%---6.7d]\n", -21));
	printf("-------\n");
	printf("%d\n", printf("[%---0-6.7d]\n", -21));
	printf("%d\n", ft_printf("[%---0-6.7d]\n", -21));
	printf("-------\n");
	printf("%d\n", printf("[%7.-1d]\n", -92));
	printf("%d\n", ft_printf("[%7.-1d]\n", -92));
	printf("-------\n");
	printf("%d\n", printf("[%7.-6d]\n", -92));
	printf("%d\n", ft_printf("[%7.-6d]\n", -92));
	printf("-------\n");
	printf("%d\n", printf("[%7.-8d]\n", 0));
	printf("%d\n", ft_printf("[%7.-8d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%10.-8d]\n", 9));
	printf("%d\n", ft_printf("[%10.-8d]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%10.-8d]\n", 0));
	printf("%d\n", ft_printf("[%10.-8d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.-8d]\n", 9));
	printf("%d\n", ft_printf("[%07.-8d]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%07.-8d]\n", -240));
	printf("%d\n", ft_printf("[%07.-8d]\n", -240));
	printf("-------\n");
	printf("%d\n", printf("[%07.-8d]\n", 0));
	printf("%d\n", ft_printf("[%07.-8d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%010.-8d]\n", 9));
	printf("%d\n", ft_printf("[%010.-8d]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%010.-8d]\n", -0));
	printf("%d\n", ft_printf("[%010.-8d]\n", -0));
	printf("-------\n");
	printf("%d\n", printf("[%-07.-8d]\n", 9));
	printf("%d\n", ft_printf("[%-07.-8d]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%-07.-8d]\n", 0));
	printf("%d\n", ft_printf("[%-07.-8d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-8d]\n", 9));
	printf("%d\n", ft_printf("[%-010.-8d]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-0d]\n", 9));
	printf("%d\n", ft_printf("[%-010.-0d]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-8d]\n", 0));
	printf("%d\n", ft_printf("[%-010.-8d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-0d]\n", 0));
	printf("%d\n", ft_printf("[%-010.-0d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-d]\n", 9));
	printf("%d\n", ft_printf("[%-010.-d]\n", 9));
	printf("       \n");

	printf("U TEST\n");
	printf("%d\n", printf("[%9.7u]\n", 23));
	printf("%d\n", ft_printf("[%9.7u]\n", 23));
	printf("-------\n");
	printf("%d\n", printf("[%09.7u]\n", 21));
	printf("%d\n", ft_printf("[%09.7u]\n", 21));
	printf("-------\n");
	printf("%d\n", printf("[%7.9u]\n", 21));
	printf("%d\n", ft_printf("[%7.9u]\n", 21));
	printf("-------\n");
	printf("%d\n", printf("[%07.9u]\n", -56));
	printf("%d\n", ft_printf("[%07.9u]\n", -56));
	printf("-------\n");
	printf("%d\n", printf("[%-7.9u]\n", 35780));
	printf("%d\n", ft_printf("[%-7.9u]\n", 35780));
	printf("-------\n");
	printf("%d\n", printf("[%-07.9u]\n", 256));
	printf("%d\n", ft_printf("[%-07.9u]\n", 256));
	printf("-------\n");
	printf("%d\n", printf("[%02.1u]\n", 235));
	printf("%d\n", ft_printf("[%02.1u]\n", 235));
	printf("-------\n");
	printf("%d\n", printf("[%010.u]\n", -235));
	printf("%d\n", ft_printf("[%010.u]\n", -235));
	printf("-------\n");
	printf("%d\n", printf("[%010.*u]\n", -4, 235));
	printf("%d\n", ft_printf("[%010.*u]\n", -4, 235));
	printf("-------\n");
	printf("%d\n", printf("[%*.9u]\n", -7, 23));
	printf("%d\n", ft_printf("[%*.9u]\n", -7, 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.*u]\n", -9, 23));
	printf("%d\n", ft_printf("[%7.*u]\n", -9, 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.*u]\n", 0, 23));
	printf("%d\n", ft_printf("[%7.*u]\n", 0, 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.u]\n", 23));
	printf("%d\n", ft_printf("[%7.u]\n", 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.0u]\n", 23));
	printf("%d\n", ft_printf("[%7.0u]\n", 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.-0u]\n", 23));
	printf("%d\n", ft_printf("[%7.-0u]\n", 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.*u]\n", -0, 23));
	printf("%d\n", ft_printf("[%7.*u]\n", -0, 23));
	printf("-------\n");
	printf("%d\n", printf("[%07.*u]\n", -9, 0));
	printf("%d\n", ft_printf("[%07.*u]\n", -9, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*u]\n", 0, 0));
	printf("%d\n", ft_printf("[%07.*u]\n", 0, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*u]\n", -0, 0));
	printf("%d\n", ft_printf("[%07.*u]\n", -0, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.u]\n", 0));
	printf("%d\n", ft_printf("[%07.u]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.0u]\n", 0));
	printf("%d\n", ft_printf("[%07.0u]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.-0u]\n", 0));
	printf("%d\n", ft_printf("[%07.-0u]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*u]\n", -9, 0));
	printf("%d\n", ft_printf("[%07.*u]\n", -9, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*u]\n", 0, 0));
	printf("%d\n", ft_printf("[%07.*u]\n", 0, 0));
	printf("-------\n");
	printf("%d\n", printf("[min%04.*uint]\n", 20, 4294967295));
	printf("%d\n", ft_printf("[min%04.*uint]\n", 20, 4294967295));
	printf("-------\n");
	printf("%d\n", printf("[min%04.*uint]\n", 20, -4294967295));
	printf("%d\n", ft_printf("[min%04.*uint]\n", 20, -4294967295));
	printf("-------\n");
	printf("%d\n", printf("[max%-04.*uint]\n", -20, 4294967296));
	printf("%d\n", ft_printf("[max%-04.*uint]\n", -20, 4294967296));
	printf("-------\n");
	printf("%d\n", printf("[aa%04ubb]\n", -42));
	printf("%d\n", ft_printf("[aa%04ubb]\n", -42));
	printf("-------\n");
	printf("%d\n", printf("[%007u]\n", -21));
	printf("%d\n", ft_printf("[%007u]\n", -21));
	printf("-------\n");
	printf("%d\n", printf("[%0000--8u]\n", -21));
	printf("%d\n", ft_printf("[%0000--8u]\n", -21));
	printf("-------\n");
	printf("%d\n", printf("[%---6.5u]\n", 21));
	printf("%d\n", ft_printf("[%---6.5u]\n", 21));
	printf("-------\n");
	printf("%d\n", printf("[%---6.7u]\n", -21));
	printf("%d\n", ft_printf("[%---6.7u]\n", -21));
	printf("-------\n");
	printf("%d\n", printf("[%7.-1u]\n", -92));
	printf("%d\n", ft_printf("[%7.-1u]\n", -92));
	printf("-------\n");
	printf("%d\n", printf("[%7.-6u]\n", -92));
	printf("%d\n", ft_printf("[%7.-6u]\n", -92));
	printf("-------\n");
	printf("%d\n", printf("[%7.-8u]\n", 0));
	printf("%d\n", ft_printf("[%7.-8u]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%10.-8u]\n", 9));
	printf("%d\n", ft_printf("[%10.-8u]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%10.-8u]\n", 0));
	printf("%d\n", ft_printf("[%10.-8u]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.-8u]\n", 9));
	printf("%d\n", ft_printf("[%07.-8u]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%07.-8u]\n", -240));
	printf("%d\n", ft_printf("[%07.-8u]\n", -240));
	printf("-------\n");
	printf("%d\n", printf("[%07.-8u]\n", 0));
	printf("%d\n", ft_printf("[%07.-8u]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%010.-8u]\n", 9));
	printf("%d\n", ft_printf("[%010.-8u]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%010.-8u]\n", -0));
	printf("%d\n", ft_printf("[%010.-8u]\n", -0));
	printf("-------\n");
	printf("%d\n", printf("[%-07.-8u]\n", 9));
	printf("%d\n", ft_printf("[%-07.-8u]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%-07.-8u]\n", 0));
	printf("%d\n", ft_printf("[%-07.-8u]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-8u]\n", 9));
	printf("%d\n", ft_printf("[%-010.-8u]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-0u]\n", 9));
	printf("%d\n", ft_printf("[%-010.-0u]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-8u]\n", 0));
	printf("%d\n", ft_printf("[%-010.-8u]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-0u]\n", 0));
	printf("%d\n", ft_printf("[%-010.-0u]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-u]\n", 9));
	printf("%d\n", ft_printf("[%-010.-u]\n", 9));
	printf("       \n");


	printf("X TEST\n");
	printf("%d\n", printf("[%9.7x]\n", 23));
	printf("%d\n", ft_printf("[%9.7x]\n", 23));
	printf("-------\n");
	printf("%d\n", printf("[%09.7x]\n", 21));
	printf("%d\n", ft_printf("[%09.7x]\n", 21));
	printf("-------\n");
	printf("%d\n", printf("[%7.9X]\n", 21));
	printf("%d\n", ft_printf("[%7.9X]\n", 21));
	printf("-------\n");
	printf("%d\n", printf("[%07.9X]\n", -56));
	printf("%d\n", ft_printf("[%07.9X]\n", -56));
	printf("-------\n");
	printf("%d\n", printf("[%-7.9x]\n", 3578));
	printf("%d\n", ft_printf("[%-7.9x]\n", 3578));
	printf("-------\n");
	printf("%d\n", printf("[%-07.9x]\n", 256));
	printf("%d\n", ft_printf("[%-07.9x]\n", 256));
	printf("-------\n");
	printf("%d\n", printf("[%02.1x]\n", 235));
	printf("%d\n", ft_printf("[%02.1x]\n", 235));
	printf("-------\n");
	printf("%d\n", printf("[%010.x]\n", -235));
	printf("%d\n", ft_printf("[%010.x]\n", -235));
	printf("-------\n");
	printf("%d\n", printf("[%010.*x]\n", -4, 235));
	printf("%d\n", ft_printf("[%010.*x]\n", -4, 235));
	printf("-------\n");
	printf("%d\n", printf("[%*.9x]\n", -7, 23));
	printf("%d\n", ft_printf("[%*.9x]\n", -7, 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.*x]\n", -9, 23));
	printf("%d\n", ft_printf("[%7.*x]\n", -9, 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.*x]\n", 0, 23));
	printf("%d\n", ft_printf("[%7.*x]\n", 0, 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.x]\n", 23));
	printf("%d\n", ft_printf("[%7.x]\n", 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.0X]\n", 23));
	printf("%d\n", ft_printf("[%7.0X]\n", 23));
	printf("-------\n");
	printf("%d\n", printf("[%07.-0X]\n", 23));
	printf("%d\n", ft_printf("[%07.-0X]\n", 23));
	printf("-------\n");
	printf("%d\n", printf("[%*.*X]\n", -7, -0, 23));
	printf("%d\n", ft_printf("[%*.*X]\n", -7, -0, 23));
	printf("-------\n");
	printf("%d\n", printf("[%07.*x]\n", -9, 0));
	printf("%d\n", ft_printf("[%07.*x]\n", -9, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*x]\n", 0, 0));
	printf("%d\n", ft_printf("[%07.*x]\n", 0, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*x]\n", -0, 0));
	printf("%d\n", ft_printf("[%07.*x]\n", -0, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.x]\n", 0));
	printf("%d\n", ft_printf("[%07.x]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.0X]\n", 0));
	printf("%d\n", ft_printf("[%07.0X]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.-0X]\n", 0));
	printf("%d\n", ft_printf("[%07.-0X]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*X]\n", -9, 0));
	printf("%d\n", ft_printf("[%07.*X]\n", -9, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*x]\n", 0, 0));
	printf("%d\n", ft_printf("[%07.*x]\n", 0, 0));
	printf("-------\n");
	printf("%d\n", printf("[min%04.*xint]\n", 20, -2147483648));
	printf("%d\n", ft_printf("[min%04.*xint]\n", 20, -2147483648));
	printf("-------\n");
	printf("%d\n", printf("[min%04.*xxint]\n", 20, -2147483650));
	printf("%d\n", ft_printf("[min%04.*xxint]\n", 20, -2147483650));
	printf("-------\n");
	printf("%d\n", printf("[max%-04.*xXint]\n", -20, 2147483647));
	printf("%d\n", ft_printf("[max%-04.*xXint]\n", -20, 2147483647));
	printf("-------\n");
	printf("%d\n", printf("[max%-04.*xint]\n", -20, 2147483650));
	printf("%d\n", ft_printf("[max%-04.*xint]\n", -20, 2147483650));
	printf("-------\n");
	printf("%d\n", printf("[aa%04xbb]\n", -42));
	printf("%d\n", ft_printf("[aa%04xbb]\n", -42));
	printf("-------\n");
	printf("%d\n", printf("[%007x]\n", -21));
	printf("%d\n", ft_printf("[%007x]\n", -21));
	printf("-------\n");
	printf("%d\n", printf("[%0000--8x]\n", -21));
	printf("%d\n", ft_printf("[%0000--8x]\n", -21));
	printf("-------\n");
	printf("%d\n", printf("[%---6.5x]\n", 21));
	printf("%d\n", ft_printf("[%---6.5x]\n", 21));
	printf("-------\n");
	printf("%d\n", printf("[%---6.7x]\n", -21));
	printf("%d\n", ft_printf("[%---6.7x]\n", -21));
	printf("-------\n");
	printf("%d\n", printf("[%7.-1x]\n", -92));
	printf("%d\n", ft_printf("[%7.-1x]\n", -92));
	printf("-------\n");
	printf("%d\n", printf("[%7.-6x]\n", -92));
	printf("%d\n", ft_printf("[%7.-6x]\n", -92));
	printf("-------\n");
	printf("%d\n", printf("[%7.-8x]\n", 0));
	printf("%d\n", ft_printf("[%7.-8x]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%10.-8x]\n", 9));
	printf("%d\n", ft_printf("[%10.-8x]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%10.-8d]\n", 0));
	printf("%d\n", ft_printf("[%10.-8d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.-8d]\n", 9));
	printf("%d\n", ft_printf("[%07.-8d]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%07.-8d]\n", -240));
	printf("%d\n", ft_printf("[%07.-8d]\n", -240));
	printf("-------\n");
	printf("%d\n", printf("[%07.-8d]\n", 0));
	printf("%d\n", ft_printf("[%07.-8d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%010.-8x]\n", 9));
	printf("%d\n", ft_printf("[%010.-8x]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%010.-8x]\n", -0));
	printf("%d\n", ft_printf("[%010.-8x]\n", -0));
	printf("-------\n");
	printf("%d\n", printf("[%-07.-8x]\n", 9));
	printf("%d\n", ft_printf("[%-07.-8x]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%-07.-8x]\n", 0));
	printf("%d\n", ft_printf("[%-07.-8x]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-8x]\n", 16));
	printf("%d\n", ft_printf("[%-010.-8x]\n", 16));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-0x]\n", 240));
	printf("%d\n", ft_printf("[%-010.-0x]\n", 240));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-8x]\n", -300));
	printf("%d\n", ft_printf("[%-010.-8x]\n", -300));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-0x]\n", 0));
	printf("%d\n", ft_printf("[%-010.-0x]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-x]\n", 42));
	printf("%d\n", ft_printf("[%-010.-x]\n", 42));
	printf("       \n");
/*
	printf("S TEST\n");
	printf("%d\n", printf("[%42s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%42s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%11s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%11s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%1s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%1s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%-42s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%-42s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%-11s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%-11s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%-1s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%-1s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%042s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%042s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%011s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%011s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%01s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%01s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%-01s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%-01s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%.21s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%.21s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%.s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%.s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%.4s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%.4s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%.11s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%.11s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%*s]\n", 21, "Jabberwocky"));
	printf("%d\n", ft_printf("[%*s]\n", 21, "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%*s]\n", -9, "Jabberwocky"));
	printf("%d\n", ft_printf("[%*s]\n", -9, "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%.*s]\n", -0, "Jabberwocky"));
	printf("%d\n", ft_printf("[%.*s]\n", -0, "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%.*s]\n", 4, "Jabberwocky"));
	printf("%d\n", ft_printf("[%.*s]\n", 4, "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%.*s]\n", -4, "Jabberwocky"));
	printf("%d\n", ft_printf("[%.*s]\n", -4, "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%.*s]\n", -0, "Jabberwocky"));
	printf("%d\n", ft_printf("[%.*s]\n", -0, "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%-*.*s]\n", 11, 5, "Jabberwocky"));
	printf("%d\n", ft_printf("[%-*.*s]\n", 11, 5, "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%-0*.*s]\n", 1, -5, "Jabberwocky"));
	printf("%d\n", ft_printf("[%-0*.*s]\n", 1, -5, "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%0*.*s]\n", -7, 5, "Jabberwocky"));
	printf("%d\n", ft_printf("[%0*.*s]\n", -7, 5, "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%.-6s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%.-6s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%7.-0s]\n", "hello"));
	printf("%d\n", ft_printf("[%7.-0s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%-07.2s]\n", "hello"));
	printf("%d\n", ft_printf("[%-07.2s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%-9.7s]\n", "hello"));
	printf("%d\n", ft_printf("[%-9.7s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%09.4s]\n", "hello"));
	printf("%d\n", ft_printf("[%09.4s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%7.3s]\n", "hello"));
	printf("%d\n", ft_printf("[%7.3s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%07.0s]\n", "hello"));
	printf("%d\n", ft_printf("[%07.0s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%07.s]\n", "hello"));
	printf("%d\n", ft_printf("[%07.s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%07.*s]\n", 0, "hello"));
	printf("%d\n", ft_printf("[%07.*s]\n", 0, "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%-07.*s]\n", -0, "hello"));
	printf("%d\n", ft_printf("[%-07.*s]\n", -0, "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%07.*s]\n", -3, "hello"));
	printf("%d\n", ft_printf("[%07.*s]\n", -3, "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%07.0s]\n", "hello"));
	printf("%d\n", ft_printf("[%07.0s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%7.-0s]\n", "hello"));
	printf("%d\n", ft_printf("[%7.-0s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%-7.1s]\n", "hello"));
	printf("%d\n", ft_printf("[%-7.1s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%-07.4s]\n", "hello"));
	printf("%d\n", ft_printf("[%-07.4s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%02.1s]\n", "hello"));
	printf("%d\n", ft_printf("[%02.1s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%010.s]\n", "hello"));
	printf("%d\n", ft_printf("[%010.s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%010.*s]\n", -4, "hello"));
	printf("%d\n", ft_printf("[%010.*s]\n", -4, "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%*.9s]\n", -7, "hello"));
	printf("%d\n", ft_printf("[%*.9s]\n", -7, "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%7.*s]\n", -9, "hello"));
	printf("%d\n", ft_printf("[%7.*s]\n", -9, "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%7.*s]\n", 0, "hello"));
	printf("%d\n", ft_printf("[%7.*s]\n", 0, "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%7.s]\n", "hello"));
	printf("%d\n", ft_printf("[%7.s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%7.0s]\n", "hello"));
	printf("%d\n", ft_printf("[%7.0s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%07.-0s]\n", "hello"));
	printf("%d\n", ft_printf("[%07.-0s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%7.*s]\n", -0, "hello"));
	printf("%d\n", ft_printf("[%7.*s]\n", -0, "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%7.-3s]\n", "hello"));
	printf("%d\n", ft_printf("[%7.-3s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%-07.-3s]\n", "hello"));
	printf("%d\n", ft_printf("[%-07.-3s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%07.-3s]\n", "hello"));
	printf("%d\n", ft_printf("[%07.-3s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%07.-0s]\n", "hello"));
	printf("%d\n", ft_printf("[%07.-0s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%07.-s]\n", "hello"));
	printf("%d\n", ft_printf("[%07.-s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%07.*s]\n", -3, "hello"));
	printf("%d\n", ft_printf("[%07.*s]\n", -3, "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%07.*s]\n", -0, "hello"));
	printf("%d\n", ft_printf("[%07.*s]\n", -0, "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%7.*s]\n", -10, "hello"));
	printf("%d\n", ft_printf("[%7.*s]\n", -10, "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%07.s]\n", "hello"));
	printf("%d\n", ft_printf("[%07.s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%7.-3s]\n", "\0"));
	printf("%d\n", ft_printf("[%7.-3s]\n", "\0"));
	printf("-------\n");
	printf("%d\n", printf("[%-07.-3s]\n", "\0"));
	printf("%d\n", ft_printf("[%-07.-3s]\n", "\0"));
	printf("-------\n");
	printf("%d\n", printf("[%07.-0s]\n", "\0"));
	printf("%d\n", ft_printf("[%07.-0s]\n", "\0"));
	printf("-------\n");
	printf("%d\n", printf("[%07.-s]\n", "\0"));
	printf("%d\n", ft_printf("[%07.-s]\n", "\0"));
	printf("-------\n");
	printf("%d\n", printf("[%07.*s]\n", -3, "\0"));
	printf("%d\n", ft_printf("[%07.*s]\n", -3, "\0"));
	printf("-------\n");
	printf("%d\n", printf("[%07.*s]\n", -0, "\0"));
	printf("%d\n", ft_printf("[%07.*s]\n", -0, "\0"));
	printf("-------\n");
	printf("%d\n", printf("[%7.*s]\n", -10, "\0"));
	printf("%d\n", ft_printf("[%7.*s]\n", -10, "\0"));
	printf("-------\n");
	printf("%d\n", printf("[%07.s]\n", "\0"));
	printf("%d\n", ft_printf("[%07.s]\n", "\0"));
	printf("-------\n");
	printf("%d\n", printf("[%07.0s]\n", "\0"));
	printf("%d\n", ft_printf("[%07.0s]\n", "\0"));
	printf("-------\n");
	printf("%d\n", printf("[%07.-0s]\n", NULL));
	printf("%d\n", ft_printf("[%07.-0s]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%07.-2s]\n", NULL));
	printf("%d\n", ft_printf("[%07.-2s]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%07.s]\n", NULL));
	printf("%d\n", ft_printf("[%07.s]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%07.0s]\n", NULL));
	printf("%d\n", ft_printf("[%07.0s]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%07.*s]\n", -1, NULL));
	printf("%d\n", ft_printf("[%07.*s]\n", -1, NULL));
	printf("-------\n");
	printf("%d\n", printf("[%020.*s]\n", 2, NULL));
	printf("%d\n", ft_printf("[%020.*s]\n", 2, NULL));
	printf("-------\n");
	printf("%d\n", printf("[%020.*s]\n", 10, NULL));
	printf("%d\n", ft_printf("[%020.*s]\n", 10, NULL));
	printf("-------\n");
	printf("%d\n", printf("[%10.3s]\n", NULL));
	printf("%d\n", ft_printf("[%10.3s]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%s]\n", "\0"));
	printf("%d\n", ft_printf("[%s]\n", "\0"));
	printf("-------\n");
	printf("%d\n", printf("[%.10s]\n", "\0"));
	printf("%d\n", ft_printf("[%.10s]\n", "\0"));
	printf("-------\n");
	printf("%d\n", printf("[%10.10s]\n", "\0"));
	printf("%d\n", ft_printf("[%10.10s]\n", "\0"));
	printf("-------\n");
	printf("%d\n", printf("[%-3s]\n", "aa"));
	printf("%d\n", ft_printf("[%-3s]\n", "aa"));
	printf("-------\n");
	printf("%d\n", printf("[%.*s]\n", -10, "bbbb"));
	printf("%d\n", ft_printf("[%.*s]\n", -10, "bbbb"));
	printf("-------\n");
	printf("%d\n", printf("[%.s]\n", "aaa"));
	printf("%d\n", ft_printf("[%.s]\n", "aaa"));
	printf("-------\n");
	printf("%d\n", printf("[%.2s]\n", "aaa"));
	printf("%d\n", ft_printf("[%.2s]\n", "aaa"));
	printf("-------\n");
	printf("%d\n", printf("[%07.*s]\n", -9, "\0"));
	printf("%d\n", ft_printf("[%07.*s]\n", -9, "\0"));
	printf("-------\n");
	printf("%d\n", printf("[%07.*s]\n", 0, "\0"));
	printf("%d\n", ft_printf("[%07.*s]\n", 0, "\0"));
	printf("-------\n");
	printf("%d\n", printf("[%07.*s]\n", -0, "\0"));
	printf("%d\n", ft_printf("[%07.*s]\n", -0, "\0"));
	printf("-------\n");
	printf("%d\n", printf("[%07.s]\n", "\0"));
	printf("%d\n", ft_printf("[%07.s]\n", "\0"));
	printf("-------\n");
	printf("%d\n", printf("[%07.0s]\n", "\0"));
	printf("%d\n", ft_printf("[%07.0s]\n", "\0"));
	printf("-------\n");
	printf("%d\n", printf("[%07.-0s]\n", "\0"));
	printf("%d\n", ft_printf("[%07.-0s]\n", "\0"));
	printf("-------\n");
	printf("%d\n", printf("[%07.*s]\n", -9, "\0"));
	printf("%d\n", ft_printf("[%07.*s]\n", -9, "\0"));
	printf("-------\n");
	printf("%d\n", printf("[%07.*s]\n", 0, "\0"));
	printf("%d\n", ft_printf("[%07.*s]\n", 0, "\0"));
	printf("-------\n");
	printf("%d\n", printf("[aa%04sbb]\n", "aabb"));
	printf("%d\n", ft_printf("[aa%04sbb]\n", "aabb"));
	printf("-------\n");
	printf("%d\n", printf("[%007s]\n", "foooo"));
	printf("%d\n", ft_printf("[%007s]\n", "foooo"));
	printf("-------\n");
	printf("%d\n", printf("[%0000--8s]\n", "bar"));
	printf("%d\n", ft_printf("[%0000--8s]\n", "bar"));
	printf("-------\n");
	printf("%d\n", printf("[%---6.5s]\n", "aabb"));
	printf("%d\n", ft_printf("[%---6.5s]\n", "aabb"));
	printf("-------\n");
	printf("%d\n", printf("[%---6.7s]\n", "aabb"));
	printf("%d\n", ft_printf("[%---6.7s]\n", "aabb"));
	printf("       \n");

	printf("C TEST\n");
	printf("%d\n", printf("[%.3c]\n", 'a'));
	printf("%d\n", ft_printf("[%.3c]\n", 'a'));
	printf("-------\n");
	printf("%d\n", printf("[%7.3c]\n", 'a'));
	printf("%d\n", ft_printf("[%7.3c]\n", 'a'));
	printf("-------\n");
	printf("%d\n", printf("[%07.1c]\n", 'a'));
	printf("%d\n", ft_printf("[%07.1c]\n", 'a'));
	printf("-------\n");
	printf("%d\n", printf("[%-0*c]\n", 10, 'a'));
	printf("%d\n", ft_printf("[%-0*c]\n", 10, 'a'));
	printf("-------\n");
	printf("%d\n", printf("[%07.3c]\n", 'a'));
	printf("%d\n", ft_printf("[%07.3c]\n", 'a'));
	printf("-------\n");
	printf("%d\n", printf("[%7.3c]\n", 'a'));
	printf("%d\n", ft_printf("[%7.3c]\n", 'a'));
	printf("-------\n");
	printf("%d\n", printf("[%07.1c]\n", 'a'));
	printf("%d\n", ft_printf("[%07.1c]\n", 'a'));
	printf("-------\n");
	printf("%d\n", printf("[%7.1c]\n", 'a'));
	printf("%d\n", ft_printf("[%7.1c]\n", 'a'));
	printf("-------\n");
	printf("%d\n", printf("[%07.-3c]\n", 'a'));
	printf("%d\n", ft_printf("[%07.-3c]\n", 'a'));
	printf("-------\n");
	printf("%d\n", printf("[%-07.-3c]\n", 'a'));
	printf("%d\n", ft_printf("[%-07.-3c]\n", 'a'));
	printf("-------\n");
	printf("%d\n", printf("[%07.-3c]\n", 'a'));
	printf("%d\n", ft_printf("[%07.-3c]\n", 'a'));
	printf("-------\n");
	printf("%d\n", printf("[%07.-0c]\n", 'a'));
	printf("%d\n", ft_printf("[%07.-0c]\n", 'a'));
	printf("-------\n");
	printf("%d\n", printf("[%07.*c]\n", -0, 'a'));
	printf("%d\n", ft_printf("[%07.*c]\n", -0, 'a'));
	printf("-------\n");
	printf("%d\n", printf("[%07.-c]\n", 'a'));
	printf("%d\n", ft_printf("[%07.-c]\n", 'a'));
	printf("-------\n");
	printf("%d\n", printf("[%07.*c]\n", -3, 'a'));
	printf("%d\n", ft_printf("[%07.*c]\n", -3, 'a'));
	printf("-------\n");
	printf("%d\n", printf("[%07.*c]\n", -0, 'a'));
	printf("%d\n", ft_printf("[%07.*c]\n", -0, 'a'));
	printf("-------\n");
	printf("%d\n", printf("[%7.*c]\n", -10, 'a'));
	printf("%d\n", ft_printf("[%7.*c]\n", -10, 'a'));
	printf("-------\n");
	printf("%d\n", printf("[%07.c]\n", 'a'));
	printf("%d\n", ft_printf("[%07.c]\n", 'a'));
	printf("-------\n");
	printf("%d\n", printf("[%07.0c]\n", 'a'));
	printf("%d\n", ft_printf("[%07.0c]\n", 'a'));
	printf("-------\n");
	printf("%d\n", printf("[%07.0c]\n", 'ab'));
	printf("%d\n", ft_printf("[%07.0c]\n", 'ab'));
	printf("-------\n");
	printf("%d\n", printf("[%07.-0c]\n", 'ab'));
	printf("%d\n", ft_printf("[%07.-0c]\n", 'ab'));
	printf("-------\n");
	printf("%d\n", printf("[%07.-4c]\n", 'ab'));
	printf("%d\n", ft_printf("[%07.-4c]\n", 'ab'));
	printf("-------\n");
	printf("%d\n", printf("[%07.-1c]\n", 'ab'));
	printf("%d\n", ft_printf("[%07.-1c]\n", 'ab'));
	printf("-------\n");
	printf("%d\n", printf("[%07.*c]\n", -1, 'ab'));
	printf("%d\n", ft_printf("[%07.*c]\n", -1, 'ab'));
	printf("-------\n");
	printf("%d\n", printf("[%07.*c]\n", -1, "ab"));
	printf("%d\n", ft_printf("[%07.*c]\n", -1, "ab"));
	printf("-------\n");
	printf("       \n");
	printf("%d\n", printf("[%.3c]\n", '\0'));
	printf("%d\n", ft_printf("[%.3c]\n", '\0'));
	printf("-------\n");
	printf("%d\n", printf("[%7.3c]\n", '\0'));
	printf("%d\n", ft_printf("[%7.3c]\n", '\0'));
	printf("-------\n");
	printf("%d\n", printf("[%07.1c]\n", '\0'));
	printf("%d\n", ft_printf("[%07.1c]\n", '\0'));
	printf("-------\n");
	printf("%d\n", printf("[%-0*c]\n", 10, '\0'));
	printf("%d\n", ft_printf("[%-0*c]\n", 10, '\0'));
	printf("-------\n");
	printf("%d\n", printf("[%07.3c]\n", '\0'));
	printf("%d\n", ft_printf("[%07.3c]\n", '\0'));
	printf("-------\n");
	printf("%d\n", printf("[%7.3c]\n", '\0'));
	printf("%d\n", ft_printf("[%7.3c]\n", '\0'));
	printf("-------\n");
	printf("%d\n", printf("[%07.1c]\n", '\0'));
	printf("%d\n", ft_printf("[%07.1c]\n", '\0'));
	printf("-------\n");
	printf("%d\n", printf("[%7.1c]\n", '\0'));
	printf("%d\n", ft_printf("[%7.1c]\n", '\0'));
	printf("-------\n");
	printf("%d\n", printf("[%07.-3c]\n", '\0'));
	printf("%d\n", ft_printf("[%07.-3c]\n", '\0'));
	printf("-------\n");
	printf("%d\n", printf("[%-07.-3c]\n", '\0'));
	printf("%d\n", ft_printf("[%-07.-3c]\n", '\0'));
	printf("-------\n");
	printf("%d\n", printf("[%07.-3c]\n", '\0'));
	printf("%d\n", ft_printf("[%07.-3c]\n", '\0'));
	printf("-------\n");
	printf("%d\n", printf("[%07.-0c]\n", '\0'));
	printf("%d\n", ft_printf("[%07.-0c]\n", '\0'));
	printf("-------\n");
	printf("%d\n", printf("[%07.*c]\n", -0, '\0'));
	printf("%d\n", ft_printf("[%07.*c]\n", -0, '\0'));
	printf("-------\n");
	printf("%d\n", printf("[%07.-c]\n", '\0'));
	printf("%d\n", ft_printf("[%07.-c]\n", '\0'));
	printf("-------\n");
	printf("%d\n", printf("[%07.*c]\n", -3, '\0'));
	printf("%d\n", ft_printf("[%07.*c]\n", -3, '\0'));
	printf("-------\n");
	printf("%d\n", printf("[%07.*c]\n", -0, '\0'));
	printf("%d\n", ft_printf("[%07.*c]\n", -0, '\0'));
	printf("-------\n");
	printf("%d\n", printf("[%7.*c]\n", -10, '\0'));
	printf("%d\n", ft_printf("[%7.*c]\n", -10, '\0'));
	printf("-------\n");
	printf("%d\n", printf("[%07.c]\n", '\0'));
	printf("%d\n", ft_printf("[%07.c]\n", '\0'));
	printf("-------\n");
	printf("%d\n", printf("[%07.0c]\n", '\0'));
	printf("%d\n", ft_printf("[%07.0c]\n", '\0'));
	printf("       \n");

	int d = 1;
	int *p = &d;
	char c = 'a';
	int *s = &c;

	printf("P TEST\n");
	printf("%d\n", printf("[%7p]\n", p));
	printf("%d\n", ft_printf("[%7p]\n", p));
	printf("-------\n");
	printf("%d\n", printf("[%43p]\n", p));
	printf("%d\n", ft_printf("[%43p]\n", p));
	printf("-------\n");
	printf("%d\n", printf("[%043.p]\n", p));
	printf("%d\n", ft_printf("[%043.p]\n", p));
	printf("-------\n");
	printf("%d\n", printf("[%043.*p]\n", -50, p));
	printf("%d\n", ft_printf("[%043.*p]\n", -50, p));
	printf("-------\n");
	printf("%d\n", printf("[%-43.*p]\n", -50, s));
	printf("%d\n", ft_printf("[%-43.*p]\n", -50, s));
	printf("-------\n");
	printf("%d\n", printf("[%43.*p]\n", -50, s));
	printf("%d\n", ft_printf("[%43.*p]\n", -50, s));
	printf("-------\n");
	printf("%d\n", printf("[%07p]\n", p));
	printf("%d\n", ft_printf("[%07p]\n", p));
	printf("-------\n");
	printf("%d\n", printf("[%-42p]\n", p, p));
	printf("%d\n", ft_printf("[%-42p]\n", p, p));
	printf("-------\n");
	printf("%d\n", printf("[%042p]\n", p));
	printf("%d\n", ft_printf("[%042p]\n", p));
	printf("-------\n");
	printf("%d\n", printf("[%042.3p]\n", p));
	printf("%d\n", ft_printf("[%042.3p]\n", p));
	printf("-------\n");
	printf("%d\n", printf("[%042.p]\n", p));
	printf("%d\n", ft_printf("[%042.p]\n", p));
	printf("-------\n");
	printf("%d\n", printf("[%042.0p]\n", p));
	printf("%d\n", ft_printf("[%042.0p]\n", p));
	printf("-------\n");
	printf("%d\n", printf("[%042.-0p]\n", p));
	printf("%d\n", ft_printf("[%042.-0p]\n", p));
	printf("-------\n");
	printf("%d\n", printf("[%042.*p]\n", -4, p));
	printf("%d\n", ft_printf("[%042.*p]\n", -4, p));
	printf("-------\n");
	printf("%d\n", printf("[%42.20p]\n", p));
	printf("%d\n", ft_printf("[%42.20p]\n", p));
	printf("-------\n");
	printf("%d\n", printf("[%042.20p]\n", p));
	printf("%d\n", ft_printf("[%042.20p]\n", p));
	printf("-------\n");
	printf("%d\n", printf("[%42.20p]\n", NULL));
	printf("%d\n", ft_printf("[%42.20p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%042.1p]\n", p));
	printf("%d\n", ft_printf("[%042.1p]\n", p));
	printf("-------\n");
	printf("%d\n", printf("[%042.-1p]\n", p));
	printf("%d\n", ft_printf("[%042.-1p]\n", p));
	printf("-------\n");
	printf("%d\n", printf("[%42.30p]\n", p));
	printf("%d\n", ft_printf("[%42.30p]\n", p));
	printf("-------\n");
	printf("%d\n", printf("[%42.3p]\n", p));
	printf("%d\n", ft_printf("[%42.3p]\n", p));
	printf("-------\n");
	printf("%d\n", printf("[%042.-43p]\n", p));
	printf("%d\n", ft_printf("[%042.-43p]\n", p));
	printf("-------\n");
	printf("%d\n", printf("[%-07.-43p]\n", p));
	printf("%d\n", ft_printf("[%-07.-43p]\n", p));
	printf("-------\n");
	printf("%d\n", printf("[%-021.-42p]\n", p));
	printf("%d\n", ft_printf("[%-021.-42p]\n", p));
	printf("-------\n");
	printf("%d\n", printf("[%-021.-20p]\n", p));
	printf("%d\n", ft_printf("[%-021.-20p]\n", p));
	printf("-------\n");
	printf("%d\n", printf("[%021.-43p]\n", p));
	printf("%d\n", ft_printf("[%021.-43p]\n", p));
	printf("-------\n");
	printf("%d\n", printf("[%021.-3p]\n", p));
	printf("%d\n", ft_printf("[%021.-3p]\n", p));
	printf("-------\n");
	printf("%d\n", printf("[%045.-0p]\n", p));
	printf("%d\n", ft_printf("[%045.-0p]\n", p));
	printf("-------\n");
	printf("%d\n", printf("[%020.0p]\n", p));
	printf("%d\n", ft_printf("[%020.0p]\n", p));
	printf("-------\n");
	printf("%d\n", printf("[%020.-p]\n", s));
	printf("%d\n", ft_printf("[%020.-p]\n", s));
	printf("-------\n");
	printf("%d\n", printf("[%020.*p]\n", -3, p));
	printf("%d\n", ft_printf("[%020.*p]\n", -3, p));
	printf("-------\n");
	printf("%d\n", printf("[%020.*p]\n", -0, p));
	printf("%d\n", ft_printf("[%020.*p]\n", -0, p));
	printf("-------\n");
	printf("%d\n", printf("[%020.*p]\n", 0, s));
	printf("%d\n", ft_printf("[%020.*p]\n", 0, s));
	printf("-------\n");
	printf("%d\n", printf("[%020.*p]\n", -10, p));
	printf("%d\n", ft_printf("[%020.*p]\n", -10, p));
	printf("-------\n");
	printf("%d\n", printf("[%020.p]\n", p));
	printf("%d\n", ft_printf("[%020.p]\n", p));
	printf("-------\n");
	printf("%d\n", printf("[%020.0p]\n", p));
	printf("%d\n", ft_printf("[%020.0p]\n", p));
	printf("-------\n");

	printf("%d\n", printf("[%07p]\n", NULL));
	printf("%d\n", ft_printf("[%07p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%7p]\n", NULL));
	printf("%d\n", ft_printf("[%7p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%43p]\n", NULL));
	printf("%d\n", ft_printf("[%43p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%043.p]\n", NULL));
	printf("%d\n", ft_printf("[%043.p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%043.*p]\n", -50, NULL));
	printf("%d\n", ft_printf("[%043.*p]\n", -50, NULL));
	printf("-------\n");
	printf("%d\n", printf("[%-43.*p]\n", -50, NULL));
	printf("%d\n", ft_printf("[%-43.*p]\n", -50, NULL));
	printf("-------\n");
	printf("%d\n", printf("[%43.*p]\n", -50, NULL));
	printf("%d\n", ft_printf("[%43.*p]\n", -50, NULL));
	printf("-------\n");
	printf("%d\n", printf("[%07p]\n", NULL));
	printf("%d\n", ft_printf("[%07p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%-42p]\n", NULL));
	printf("%d\n", ft_printf("[%-42p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%042p]\n", NULL));
	printf("%d\n", ft_printf("[%042p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%042.3p]\n", NULL));
	printf("%d\n", ft_printf("[%042.3p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%042.p]\n", NULL));
	printf("%d\n", ft_printf("[%042.p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%042.0p]\n", NULL));
	printf("%d\n", ft_printf("[%042.0p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%042.-0p]\n", NULL));
	printf("%d\n", ft_printf("[%042.-0p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%042.*p]\n", -4, NULL));
	printf("%d\n", ft_printf("[%042.*p]\n", -4, NULL));
	printf("-------\n");
	printf("%d\n", printf("[%42.20p]\n", NULL));
	printf("%d\n", ft_printf("[%42.20p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%042.20p]\n", NULL));
	printf("%d\n", ft_printf("[%042.20p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%42.20p]\n", NULL));
	printf("%d\n", ft_printf("[%42.20p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%042.1p]\n", NULL));
	printf("%d\n", ft_printf("[%042.1p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%042.-1p]\n", NULL));
	printf("%d\n", ft_printf("[%042.-1p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%42.30p]\n", NULL));
	printf("%d\n", ft_printf("[%42.30p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%42.1p]\n", NULL));
	printf("%d\n", ft_printf("[%42.1p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%042.-43p]\n", NULL));
	printf("%d\n", ft_printf("[%042.-43p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%-07.-43p]\n", NULL));
	printf("%d\n", ft_printf("[%-07.-43p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%-021.-42p]\n", NULL));
	printf("%d\n", ft_printf("[%-021.-42p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%-021.-20p]\n", NULL));
	printf("%d\n", ft_printf("[%-021.-20p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%021.-43p]\n", NULL));
	printf("%d\n", ft_printf("[%021.-43p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%021.-3p]\n", NULL));
	printf("%d\n", ft_printf("[%021.-3p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%045.-0p]\n", NULL));
	printf("%d\n", ft_printf("[%045.-0p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%020.0p]\n", NULL));
	printf("%d\n", ft_printf("[%020.0p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%020.-p]\n", NULL));
	printf("%d\n", ft_printf("[%020.-p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%020.*p]\n", -3, NULL));
	printf("%d\n", ft_printf("[%020.*p]\n", -3, NULL));
	printf("-------\n");
	printf("%d\n", printf("[%020.*p]\n", -0, NULL));
	printf("%d\n", ft_printf("[%020.*p]\n", -0, NULL));
	printf("-------\n");
	printf("%d\n", printf("[%01.p]\n", NULL));
	printf("%d\n", ft_printf("[%01.p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%1.p]\n", NULL));
	printf("%d\n", ft_printf("[%1.p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%5.0p]\n", NULL));
	printf("%d\n", ft_printf("[%5.0p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%5.*p]\n", -1, NULL));
	printf("%d\n", ft_printf("[%5.*p]\n", -1, NULL));
	printf("-------\n");
	printf("%d\n", printf("[%020.*p]\n", 0, NULL));
	printf("%d\n", ft_printf("[%020.*p]\n", 0, NULL));
	printf("-------\n");
	printf("%d\n", printf("[%020.*p]\n", -10, NULL));
	printf("%d\n", ft_printf("[%020.*p]\n", -10, NULL));
	printf("-------\n");
	printf("%d\n", printf("[%0.*p]\n", -10, NULL));
	printf("%d\n", ft_printf("[%0.*p]\n", -10, NULL));
	printf("-------\n");
	printf("%d\n", printf("[%020.p]\n", NULL));
	printf("%d\n", ft_printf("[%020.p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%020.0p]\n", NULL));
	printf("%d\n", ft_printf("[%020.0p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%07p]\n", NULL));
	printf("%d\n", ft_printf("[%07p]\n", NULL));
	printf("-------\n");
*/
	return (0);
}