#include "ft_printf.h"
#include <stdio.h>

int	main(void)
{
	/*
printf("%% TEST\n");

printf("set 1\n");
	ft_printf("[%%]\n");
	printf("[%%]\n");

printf("set 2\n");
	ft_printf("[%.6%]\n");
	printf("[%.6%]\n");

printf("set 3\n");
	ft_printf("[%.*%]\n", -9);
	printf("[%.*%]\n", -9);

printf("set 4\n");
	ft_printf("[%.5%]\n");
	printf("[%.5%]\n");

printf("set 5\n");
	ft_printf("[%.*%]\n", 5);
	printf("[%.*%]\n", 5);

printf("set 6\n");
	ft_printf("[%.%]\n");
	printf("[%.%]\n");

printf("set 7\n");
	ft_printf("[%.0%]\n");
	printf("[%.0%]\n");

printf("set 8\n");
	ft_printf("[%.*%]\n", 0);
	printf("[%.*%]\n", 0);

printf("set 9\n");
	ft_printf("[%3%]\n");
	printf("[%3%]\n");

printf("set 10\n");
	ft_printf("[%06%]\n");
	printf("[%06%]\n");

printf("set 11\n");
	ft_printf("[%-6%]\n");
	printf("[%-6%]\n");

printf("set 12\n");
	ft_printf("[%0-6%]\n");
	printf("[%0-6%]\n");

printf("set 13\n");
	ft_printf("[%-06%]\n");
	printf("[%-06%]\n");

printf("set 14\n");
	ft_printf("[%1%]\n");
	printf("[%1%]\n");

printf("%%xX TEST\n");

printf("set 1\n");
	ft_printf("[%x]\n", 0);
	printf("[%x]\n", 0);
	ft_printf("[%5.X]\n", 0);
	printf("[%5.X]\n", 0);

printf("set 2\n");
	ft_printf("[%-05x]\n", 4294967295);
	printf("[%-05x]\n", 4294967295);

printf("set 3\n");
	ft_printf("[%-5.7X]\n", 4294967297);
	printf("[%-5.7X]\n", 4294967297);

printf("set 4\n");
	ft_printf("[%8.*x]\n", -9, 0);
	printf("[%8.*x]\n", -9, 0);

printf("set 5\n");
	ft_printf("[%.x]\n", 42);
	printf("[%.x]\n", 42);

printf("set 6\n");
	ft_printf("[%.*X]\n", 0, 0);
	printf("[%.*X]\n", 0, 0);

printf("set 7\n");
	ft_printf("[%.0x]\n", 3);
	printf("[%.0x]\n", 3);

printf("set 8\n");
	ft_printf("[%-10.x]\n", 455);
	printf("[%-10.x]\n", 455);

printf("set 9\n");
	ft_printf("[%012.1x]\n", 111);
	printf("[%012.1x]\n", 111);

printf("set 10\n");
	ft_printf("[%.x]\n", 0);
	printf("[%.x]\n", 0);

printf("set 11\n");
	ft_printf("[%-6.3X]\n", 4294967290);
	printf("[%-6.3X]\n", 4294967290);

printf("%%c TEST\n");

printf("set 1\n");
	ft_printf("[%-7c]\n", '\0');
	printf("[%-7c]\n", '\0');
	ft_printf("[%5.c]\n", '\0');
	printf("[%5.c]\n", '\0');

printf("set 2\n");
	ft_printf("[%-5c]\n", 'a');
	printf("[%-5c]\n", 'a');

printf("set 3\n");
	ft_printf("[%5c]\n", '\0');
	printf("[%5c]\n", '\0');

printf("set 4\n");
	int my = ft_printf("[%4c]\n", '\0');
	int or = printf("[%4c]\n", '\0');
	printf("[%d]\n", my);
	printf("[%d]\n", or);
*/
/*
	printf("%d\n", printf("[%10.3s]\n", NULL));
	printf("%d\n", ft_printf("[%10.3s]\n", NULL));
	printf("%d\n", printf("[%s]\n", "\0"));
	printf("%d\n", ft_printf("[%s]\n", "\0"));
	printf("%d\n", printf("[%-3s]\n", "aa"));
	printf("%d\n", ft_printf("[%-3s]\n", "aa"));

	printf("%d\n", printf("[%.*s]\n", -10, "bbbb"));
	printf("%d\n", ft_printf("[%.*s]\n", -10, "bbbb"));
	printf("%d\n", printf("[%.s]\n", "aaa"));
	printf("%d\n", ft_printf("[%.s]\n", "aaa"));

	printf("%d\n", printf("[%.2s]\n", "aaa"));
	printf("%d\n", ft_printf("[%.2s]\n", "aaa"));
*/

	int d = 42;
	int *i = &d;
/*
	printf("BASIC TESTS\n");
	printf("%d\n", printf("[%c]\n", '\0'));
	printf("%d\n", ft_printf("[%c]\n", '\0'));
	printf("-------\n");
	printf("%d\n", printf("[%c]\n", 'a'));
	printf("%d\n", ft_printf("[%c]\n", 'a'));
	printf("-------\n");
	printf("%d\n", printf("[%s]\n", "why is a raven like a writing desk"));
	printf("%d\n", ft_printf("[%s]\n", "why is a raven like a writing desk"));
	printf("-------\n");
	printf("%d\n", printf("[%s]\n", "\0"));
	printf("%d\n", ft_printf("[%s]\n", "\0"));
	printf("-------\n");
	printf("%d\n", printf("[%p]\n", i));
	printf("%d\n", ft_printf("[%p]\n", i));
	printf("-------\n");
	printf("%d\n", printf("[%p]\n", NULL));
	printf("%d\n", ft_printf("[%p]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%d]\n", 2121));
	printf("%d\n", ft_printf("[%d]\n", 2121));
	printf("-------\n");
	printf("%d\n", printf("[%i]\n", -2121));
	printf("%d\n", ft_printf("[%i]\n", -2121));
	printf("-------\n");
	printf("%d\n", printf("[%i]\n", 0));
	printf("%d\n", ft_printf("[%i]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%u]\n", 256));
	printf("%d\n", ft_printf("[%u]\n", 256));
	printf("-------\n");
	printf("%d\n", printf("[%x]\n", 10241024));
	printf("%d\n", ft_printf("[%x]\n", 10241024));
	printf("-------\n");
	printf("%d\n", printf("[%X]\n", 10241024));
	printf("%d\n", ft_printf("[%X]\n", 10241024));
	printf("-------\n");
	printf("%d\n", printf("[%%]\n"));
	printf("%d\n", ft_printf("[%%]\n"));


	printf("FLAGS WITH S\n");
	printf("%d\n", printf("[%42s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%42s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%11s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%11s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%1s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%1s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%-42s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%-42s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%-11s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%-11s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%-1s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%-1s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%042s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%042s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%011s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%011s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%01s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%01s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%-01s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%-01s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%.21s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%.21s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%.s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%.s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%.4s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%.4s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%.11s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%.11s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%*s]\n", 21, "Jabberwocky"));
	printf("%d\n", ft_printf("[%*s]\n", 21, "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%*s]\n", -9, "Jabberwocky"));
	printf("%d\n", ft_printf("[%*s]\n", -9, "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%.*s]\n", -0, "Jabberwocky"));
	printf("%d\n", ft_printf("[%.*s]\n", -0, "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%.*s]\n", 4, "Jabberwocky"));
	printf("%d\n", ft_printf("[%.*s]\n", 4, "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%.*s]\n", -4, "Jabberwocky"));
	printf("%d\n", ft_printf("[%.*s]\n", -4, "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%.*s]\n", -0, "Jabberwocky"));
	printf("%d\n", ft_printf("[%.*s]\n", -0, "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%-*.*s]\n", 11, 5, "Jabberwocky"));
	printf("%d\n", ft_printf("[%-*.*s]\n", 11, 5, "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%-0*.*s]\n", 1, -5, "Jabberwocky"));
	printf("%d\n", ft_printf("[%-0*.*s]\n", 1, -5, "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%0*.*s]\n", -7, 5, "Jabberwocky"));
	printf("%d\n", ft_printf("[%0*.*s]\n", -7, 5, "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%.-6s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%.-6s]\n", "Jabberwocky"));
	printf("-------\n");
	*/

	printf("NORMAL DI\n");
	printf("%d\n", printf("[%9.7d]\n", 23));
	printf("%d\n", ft_printf("[%9.7d]\n", 23));
	printf("-------\n");
	printf("%d\n", printf("[%09.7d]\n", 21));
	printf("%d\n", ft_printf("[%09.7d]\n", 21));
	printf("-------\n");
	printf("%d\n", printf("[%7.9d]\n", 21));
	printf("%d\n", ft_printf("[%7.9d]\n", 21));
	printf("-------\n");
	printf("%d\n", printf("[%07.9d]\n", -56));
	printf("%d\n", ft_printf("[%07.9d]\n", -56));
	printf("-------\n");
	printf("%d\n", printf("[%-7.9d]\n", 3578));
	printf("%d\n", ft_printf("[%-7.9d]\n", 3578));
	printf("-------\n");
	printf("%d\n", printf("[%-07.9d]\n", 256));
	printf("%d\n", ft_printf("[%-07.9d]\n", 256));
	printf("-------\n");
	printf("%d\n", printf("[%02.1d]\n", 235));
	printf("%d\n", ft_printf("[%02.1d]\n", 235));
	printf("-------\n");
	printf("%d\n", printf("[%010.d]\n", -235));
	printf("%d\n", ft_printf("[%010.d]\n", -235));
	printf("-------\n");
	printf("%d\n", printf("[%010.*d]\n", -4, 235));
	printf("%d\n", ft_printf("[%010.*d]\n", -4, 235));
	printf("-------\n");
	printf("%d\n", printf("[%*.9d]\n", -7, 23));
	printf("%d\n", ft_printf("[%*.9d]\n", -7, 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.*d]\n", -9, 23));
	printf("%d\n", ft_printf("[%7.*d]\n", -9, 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.*d]\n", 0, 23));
	printf("%d\n", ft_printf("[%7.*d]\n", 0, 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.d]\n", 23));
	printf("%d\n", ft_printf("[%7.d]\n", 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.0d]\n", 23));
	printf("%d\n", ft_printf("[%7.0d]\n", 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.-0d]\n", 23));
	printf("%d\n", ft_printf("[%7.-0d]\n", 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.*d]\n", -0, 23));
	printf("%d\n", ft_printf("[%7.*d]\n", -0, 23));
	printf("-------\n");
	printf("%d\n", printf("[%07.*d]\n", -9, 0));
	printf("%d\n", ft_printf("[%07.*d]\n", -9, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*d]\n", 0, 0));
	printf("%d\n", ft_printf("[%07.*d]\n", 0, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*d]\n", -0, 0));
	printf("%d\n", ft_printf("[%07.*d]\n", -0, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.d]\n", 0));
	printf("%d\n", ft_printf("[%07.d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.0d]\n", 0));
	printf("%d\n", ft_printf("[%07.0d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.-0d]\n", 0));
	printf("%d\n", ft_printf("[%07.-0d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*d]\n", -9, 0));
	printf("%d\n", ft_printf("[%07.*d]\n", -9, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*d]\n", 0, 0));
	printf("%d\n", ft_printf("[%07.*d]\n", 0, 0));
	printf("-------\n");
	printf("%d\n", printf("[min%04.*dint]\n", 20, -2147483648));
	printf("%d\n", ft_printf("[min%04.*dint]\n", 20, -2147483648));
	printf("-------\n");
	printf("%d\n", printf("[min%04.*dint]\n", 20, -2147483650));
	printf("%d\n", ft_printf("[min%04.*dint]\n", 20, -2147483650));
	printf("-------\n");
	printf("%d\n", printf("[max%-04.*dint]\n", -20, 2147483647));
	printf("%d\n", ft_printf("[max%-04.*dint]\n", -20, 2147483647));
	printf("-------\n");
	printf("%d\n", printf("[max%-04.*dint]\n", -20, 2147483650));
	printf("%d\n", ft_printf("[max%-04.*dint]\n", -20, 2147483650));
	printf("-------\n");
	printf("%d\n", printf("[aa%04dbb]\n", -42));
	printf("%d\n", ft_printf("[aa%04dbb]\n", -42));
	printf("-------\n");
	printf("%d\n", printf("[%007d]\n", -21));
	printf("%d\n", ft_printf("[%007d]\n", -21));
	printf("-------\n");
	printf("%d\n", printf("[%0000--8d]\n", -21));
	printf("%d\n", ft_printf("[%0000--8d]\n", -21));
	printf("-------\n");
	printf("%d\n", printf("[%---6.5d]\n", 21));
	printf("%d\n", ft_printf("[%---6.5d]\n", 21));
	printf("-------\n");
	printf("%d\n", printf("[%---6.7d]\n", -21));
	printf("%d\n", ft_printf("[%---6.7d]\n", -21));
	printf("       \n");

	printf("UNDEFINED DI\n");
	printf("%d\n", printf("[%7.-1d]\n", -92));
	printf("%d\n", ft_printf("[%7.-1d]\n", -92));
	printf("-------\n");
	printf("%d\n", printf("[%7.-6d]\n", -92));
	printf("%d\n", ft_printf("[%7.-6d]\n", -92));
	printf("-------\n");
	printf("%d\n", printf("[%7.-8d]\n", 0));
	printf("%d\n", ft_printf("[%7.-8d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%10.-8d]\n", 9));
	printf("%d\n", ft_printf("[%10.-8d]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%10.-8d]\n", 0));
	printf("%d\n", ft_printf("[%10.-8d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.-8d]\n", 9));
	printf("%d\n", ft_printf("[%07.-8d]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%07.-8d]\n", -240));
	printf("%d\n", ft_printf("[%07.-8d]\n", -240));
	printf("-------\n");
	printf("%d\n", printf("[%07.-8d]\n", 0));
	printf("%d\n", ft_printf("[%07.-8d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%010.-8d]\n", 9));
	printf("%d\n", ft_printf("[%010.-8d]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%010.-8d]\n", -0));
	printf("%d\n", ft_printf("[%010.-8d]\n", -0));
	printf("-------\n");
	printf("%d\n", printf("[%-07.-8d]\n", 9));
	printf("%d\n", ft_printf("[%-07.-8d]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%-07.-8d]\n", 0));
	printf("%d\n", ft_printf("[%-07.-8d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-8d]\n", 9));
	printf("%d\n", ft_printf("[%-010.-8d]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-0d]\n", 9));
	printf("%d\n", ft_printf("[%-010.-0d]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-8d]\n", 0));
	printf("%d\n", ft_printf("[%-010.-8d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-0d]\n", 0));
	printf("%d\n", ft_printf("[%-010.-0d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-d]\n", 9));
	printf("%d\n", ft_printf("[%-010.-d]\n", 9));
	printf("       \n");

	printf("NORMAL U\n");
	printf("%d\n", printf("[%9.7u]\n", 23));
	printf("%d\n", ft_printf("[%9.7u]\n", 23));
	printf("-------\n");
	printf("%d\n", printf("[%09.7u]\n", 21));
	printf("%d\n", ft_printf("[%09.7u]\n", 21));
	printf("-------\n");
	printf("%d\n", printf("[%7.9u]\n", 21));
	printf("%d\n", ft_printf("[%7.9u]\n", 21));
	printf("-------\n");
	printf("%d\n", printf("[%07.9u]\n", -56));
	printf("%d\n", ft_printf("[%07.9u]\n", -56));
	printf("-------\n");
	printf("%d\n", printf("[%-7.9u]\n", 35780));
	printf("%d\n", ft_printf("[%-7.9u]\n", 35780));
	printf("-------\n");
	printf("%d\n", printf("[%-07.9u]\n", 256));
	printf("%d\n", ft_printf("[%-07.9u]\n", 256));
	printf("-------\n");
	printf("%d\n", printf("[%02.1u]\n", 235));
	printf("%d\n", ft_printf("[%02.1u]\n", 235));
	printf("-------\n");
	printf("%d\n", printf("[%010.u]\n", -235));
	printf("%d\n", ft_printf("[%010.u]\n", -235));
	printf("-------\n");
	printf("%d\n", printf("[%010.*u]\n", -4, 235));
	printf("%d\n", ft_printf("[%010.*u]\n", -4, 235));
	printf("-------\n");
	printf("%d\n", printf("[%*.9u]\n", -7, 23));
	printf("%d\n", ft_printf("[%*.9u]\n", -7, 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.*u]\n", -9, 23));
	printf("%d\n", ft_printf("[%7.*u]\n", -9, 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.*u]\n", 0, 23));
	printf("%d\n", ft_printf("[%7.*u]\n", 0, 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.u]\n", 23));
	printf("%d\n", ft_printf("[%7.u]\n", 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.0u]\n", 23));
	printf("%d\n", ft_printf("[%7.0u]\n", 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.-0u]\n", 23));
	printf("%d\n", ft_printf("[%7.-0u]\n", 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.*u]\n", -0, 23));
	printf("%d\n", ft_printf("[%7.*u]\n", -0, 23));
	printf("-------\n");
	printf("%d\n", printf("[%07.*u]\n", -9, 0));
	printf("%d\n", ft_printf("[%07.*u]\n", -9, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*u]\n", 0, 0));
	printf("%d\n", ft_printf("[%07.*u]\n", 0, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*u]\n", -0, 0));
	printf("%d\n", ft_printf("[%07.*u]\n", -0, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.u]\n", 0));
	printf("%d\n", ft_printf("[%07.u]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.0u]\n", 0));
	printf("%d\n", ft_printf("[%07.0u]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.-0u]\n", 0));
	printf("%d\n", ft_printf("[%07.-0u]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*u]\n", -9, 0));
	printf("%d\n", ft_printf("[%07.*u]\n", -9, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*u]\n", 0, 0));
	printf("%d\n", ft_printf("[%07.*u]\n", 0, 0));
	printf("-------\n");
	printf("%d\n", printf("[min%04.*uint]\n", 20, 4294967295));
	printf("%d\n", ft_printf("[min%04.*uint]\n", 20, 4294967295));
	printf("-------\n");
	printf("%d\n", printf("[min%04.*uint]\n", 20, -4294967295));
	printf("%d\n", ft_printf("[min%04.*uint]\n", 20, -4294967295));
	printf("-------\n");
	printf("%d\n", printf("[max%-04.*uint]\n", -20, 4294967296));
	printf("%d\n", ft_printf("[max%-04.*uint]\n", -20, 4294967296));
	printf("-------\n");
	printf("%d\n", printf("[aa%04ubb]\n", -42));
	printf("%d\n", ft_printf("[aa%04ubb]\n", -42));
	printf("-------\n");
	printf("%d\n", printf("[%007u]\n", -21));
	printf("%d\n", ft_printf("[%007u]\n", -21));
	printf("-------\n");
	printf("%d\n", printf("[%0000--8u]\n", -21));
	printf("%d\n", ft_printf("[%0000--8u]\n", -21));
	printf("-------\n");
	printf("%d\n", printf("[%---6.5u]\n", 21));
	printf("%d\n", ft_printf("[%---6.5u]\n", 21));
	printf("-------\n");
	printf("%d\n", printf("[%---6.7u]\n", -21));
	printf("%d\n", ft_printf("[%---6.7u]\n", -21));
	printf("       \n");

	printf("UNDEFINED U\n");
	printf("%d\n", printf("[%7.-1u]\n", -92));
	printf("%d\n", ft_printf("[%7.-1u]\n", -92));
	printf("-------\n");
	printf("%d\n", printf("[%7.-6u]\n", -92));
	printf("%d\n", ft_printf("[%7.-6u]\n", -92));
	printf("-------\n");
	printf("%d\n", printf("[%7.-8u]\n", 0));
	printf("%d\n", ft_printf("[%7.-8u]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%10.-8u]\n", 9));
	printf("%d\n", ft_printf("[%10.-8u]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%10.-8u]\n", 0));
	printf("%d\n", ft_printf("[%10.-8u]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.-8u]\n", 9));
	printf("%d\n", ft_printf("[%07.-8u]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%07.-8u]\n", -240));
	printf("%d\n", ft_printf("[%07.-8u]\n", -240));
	printf("-------\n");
	printf("%d\n", printf("[%07.-8u]\n", 0));
	printf("%d\n", ft_printf("[%07.-8u]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%010.-8u]\n", 9));
	printf("%d\n", ft_printf("[%010.-8u]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%010.-8u]\n", -0));
	printf("%d\n", ft_printf("[%010.-8u]\n", -0));
	printf("-------\n");
	printf("%d\n", printf("[%-07.-8u]\n", 9));
	printf("%d\n", ft_printf("[%-07.-8u]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%-07.-8u]\n", 0));
	printf("%d\n", ft_printf("[%-07.-8u]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-8u]\n", 9));
	printf("%d\n", ft_printf("[%-010.-8u]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-0u]\n", 9));
	printf("%d\n", ft_printf("[%-010.-0u]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-8u]\n", 0));
	printf("%d\n", ft_printf("[%-010.-8u]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-0u]\n", 0));
	printf("%d\n", ft_printf("[%-010.-0u]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-u]\n", 9));
	printf("%d\n", ft_printf("[%-010.-u]\n", 9));
	printf("       \n");

	return (0);
}