#include "ft_printf.h"
#include <stdio.h>

int	main(void)
{
	/*
printf("%% TEST\n");

printf("set 1\n");
	ft_printf("[%%]\n");
	printf("[%%]\n");

printf("set 2\n");
	ft_printf("[%.6%]\n");
	printf("[%.6%]\n");

printf("set 3\n");
	ft_printf("[%.*%]\n", -9);
	printf("[%.*%]\n", -9);

printf("set 4\n");
	ft_printf("[%.5%]\n");
	printf("[%.5%]\n");

printf("set 5\n");
	ft_printf("[%.*%]\n", 5);
	printf("[%.*%]\n", 5);

printf("set 6\n");
	ft_printf("[%.%]\n");
	printf("[%.%]\n");

printf("set 7\n");
	ft_printf("[%.0%]\n");
	printf("[%.0%]\n");

printf("set 8\n");
	ft_printf("[%.*%]\n", 0);
	printf("[%.*%]\n", 0);

printf("set 9\n");
	ft_printf("[%3%]\n");
	printf("[%3%]\n");

printf("set 10\n");
	ft_printf("[%06%]\n");
	printf("[%06%]\n");

printf("set 11\n");
	ft_printf("[%-6%]\n");
	printf("[%-6%]\n");

printf("set 12\n");
	ft_printf("[%0-6%]\n");
	printf("[%0-6%]\n");

printf("set 13\n");
	ft_printf("[%-06%]\n");
	printf("[%-06%]\n");

printf("set 14\n");
	ft_printf("[%1%]\n");
	printf("[%1%]\n");

/*
	printf("%d\n", printf("[%10.3s]\n", NULL));
	printf("%d\n", ft_printf("[%10.3s]\n", NULL));
	printf("%d\n", printf("[%s]\n", "\0"));
	printf("%d\n", ft_printf("[%s]\n", "\0"));
	printf("%d\n", printf("[%-3s]\n", "aa"));
	printf("%d\n", ft_printf("[%-3s]\n", "aa"));

	printf("%d\n", printf("[%.*s]\n", -10, "bbbb"));
	printf("%d\n", ft_printf("[%.*s]\n", -10, "bbbb"));
	printf("%d\n", printf("[%.s]\n", "aaa"));
	printf("%d\n", ft_printf("[%.s]\n", "aaa"));

	printf("%d\n", printf("[%.2s]\n", "aaa"));
	printf("%d\n", ft_printf("[%.2s]\n", "aaa"));
*/
/*
	printf("NORMAL DI\n");
	printf("%d\n", printf("[%9.7d]\n", 23));
	printf("%d\n", ft_printf("[%9.7d]\n", 23));
	printf("-------\n");
	printf("%d\n", printf("[%09.7d]\n", 21));
	printf("%d\n", ft_printf("[%09.7d]\n", 21));
	printf("-------\n");
	printf("%d\n", printf("[%7.9d]\n", 21));
	printf("%d\n", ft_printf("[%7.9d]\n", 21));
	printf("-------\n");
	printf("%d\n", printf("[%07.9d]\n", -56));
	printf("%d\n", ft_printf("[%07.9d]\n", -56));
	printf("-------\n");
	printf("%d\n", printf("[%-7.9d]\n", 3578));
	printf("%d\n", ft_printf("[%-7.9d]\n", 3578));
	printf("-------\n");
	printf("%d\n", printf("[%-07.9d]\n", 256));
	printf("%d\n", ft_printf("[%-07.9d]\n", 256));
	printf("-------\n");
	printf("%d\n", printf("[%02.1d]\n", 235));
	printf("%d\n", ft_printf("[%02.1d]\n", 235));
	printf("-------\n");
	printf("%d\n", printf("[%010.d]\n", -235));
	printf("%d\n", ft_printf("[%010.d]\n", -235));
	printf("-------\n");
	printf("%d\n", printf("[%010.*d]\n", -4, 235));
	printf("%d\n", ft_printf("[%010.*d]\n", -4, 235));
	printf("-------\n");
	printf("%d\n", printf("[%*.9d]\n", -7, 23));
	printf("%d\n", ft_printf("[%*.9d]\n", -7, 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.*d]\n", -9, 23));
	printf("%d\n", ft_printf("[%7.*d]\n", -9, 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.*d]\n", 0, 23));
	printf("%d\n", ft_printf("[%7.*d]\n", 0, 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.d]\n", 23));
	printf("%d\n", ft_printf("[%7.d]\n", 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.0d]\n", 23));
	printf("%d\n", ft_printf("[%7.0d]\n", 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.-0d]\n", 23));
	printf("%d\n", ft_printf("[%7.-0d]\n", 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.*d]\n", -0, 23));
	printf("%d\n", ft_printf("[%7.*d]\n", -0, 23));
	printf("-------\n");
	printf("%d\n", printf("[%07.*d]\n", -9, 0));
	printf("%d\n", ft_printf("[%07.*d]\n", -9, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*d]\n", 0, 0));
	printf("%d\n", ft_printf("[%07.*d]\n", 0, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*d]\n", -0, 0));
	printf("%d\n", ft_printf("[%07.*d]\n", -0, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.d]\n", 0));
	printf("%d\n", ft_printf("[%07.d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.0d]\n", 0));
	printf("%d\n", ft_printf("[%07.0d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.-0d]\n", 0));
	printf("%d\n", ft_printf("[%07.-0d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*d]\n", -9, 0));
	printf("%d\n", ft_printf("[%07.*d]\n", -9, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*d]\n", 0, 0));
	printf("%d\n", ft_printf("[%07.*d]\n", 0, 0));
	printf("-------\n");
	printf("%d\n", printf("[min%04.*dint]\n", 20, -2147483648));
	printf("%d\n", ft_printf("[min%04.*dint]\n", 20, -2147483648));
	printf("-------\n");
	printf("%d\n", printf("[min%04.*dint]\n", 20, -2147483650));
	printf("%d\n", ft_printf("[min%04.*dint]\n", 20, -2147483650));
	printf("-------\n");
	printf("%d\n", printf("[max%-04.*dint]\n", -20, 2147483647));
	printf("%d\n", ft_printf("[max%-04.*dint]\n", -20, 2147483647));
	printf("-------\n");
	printf("%d\n", printf("[max%-04.*dint]\n", -20, 2147483650));
	printf("%d\n", ft_printf("[max%-04.*dint]\n", -20, 2147483650));
	printf("-------\n");
	printf("%d\n", printf("[aa%04dbb]\n", -42));
	printf("%d\n", ft_printf("[aa%04dbb]\n", -42));
	printf("-------\n");
	printf("%d\n", printf("[%007d]\n", -21));
	printf("%d\n", ft_printf("[%007d]\n", -21));
	printf("-------\n");
	printf("%d\n", printf("[%0000--8d]\n", -21));
	printf("%d\n", ft_printf("[%0000--8d]\n", -21));
	printf("-------\n");
	printf("%d\n", printf("[%---6.5d]\n", 21));
	printf("%d\n", ft_printf("[%---6.5d]\n", 21));
	printf("-------\n");
	printf("%d\n", printf("[%---6.7d]\n", -21));
	printf("%d\n", ft_printf("[%---6.7d]\n", -21));
	printf("       \n");

	printf("UNDEFINED DI\n");
	printf("%d\n", printf("[%7.-1d]\n", -92));
	printf("%d\n", ft_printf("[%7.-1d]\n", -92));
	printf("-------\n");
	printf("%d\n", printf("[%7.-6d]\n", -92));
	printf("%d\n", ft_printf("[%7.-6d]\n", -92));
	printf("-------\n");
	printf("%d\n", printf("[%7.-8d]\n", 0));
	printf("%d\n", ft_printf("[%7.-8d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%10.-8d]\n", 9));
	printf("%d\n", ft_printf("[%10.-8d]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%10.-8d]\n", 0));
	printf("%d\n", ft_printf("[%10.-8d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.-8d]\n", 9));
	printf("%d\n", ft_printf("[%07.-8d]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%07.-8d]\n", -240));
	printf("%d\n", ft_printf("[%07.-8d]\n", -240));
	printf("-------\n");
	printf("%d\n", printf("[%07.-8d]\n", 0));
	printf("%d\n", ft_printf("[%07.-8d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%010.-8d]\n", 9));
	printf("%d\n", ft_printf("[%010.-8d]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%010.-8d]\n", -0));
	printf("%d\n", ft_printf("[%010.-8d]\n", -0));
	printf("-------\n");
	printf("%d\n", printf("[%-07.-8d]\n", 9));
	printf("%d\n", ft_printf("[%-07.-8d]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%-07.-8d]\n", 0));
	printf("%d\n", ft_printf("[%-07.-8d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-8d]\n", 9));
	printf("%d\n", ft_printf("[%-010.-8d]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-0d]\n", 9));
	printf("%d\n", ft_printf("[%-010.-0d]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-8d]\n", 0));
	printf("%d\n", ft_printf("[%-010.-8d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-0d]\n", 0));
	printf("%d\n", ft_printf("[%-010.-0d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-d]\n", 9));
	printf("%d\n", ft_printf("[%-010.-d]\n", 9));
	printf("       \n");

	printf("NORMAL U\n");
	printf("%d\n", printf("[%9.7u]\n", 23));
	printf("%d\n", ft_printf("[%9.7u]\n", 23));
	printf("-------\n");
	printf("%d\n", printf("[%09.7u]\n", 21));
	printf("%d\n", ft_printf("[%09.7u]\n", 21));
	printf("-------\n");
	printf("%d\n", printf("[%7.9u]\n", 21));
	printf("%d\n", ft_printf("[%7.9u]\n", 21));
	printf("-------\n");
	printf("%d\n", printf("[%07.9u]\n", -56));
	printf("%d\n", ft_printf("[%07.9u]\n", -56));
	printf("-------\n");
	printf("%d\n", printf("[%-7.9u]\n", 35780));
	printf("%d\n", ft_printf("[%-7.9u]\n", 35780));
	printf("-------\n");
	printf("%d\n", printf("[%-07.9u]\n", 256));
	printf("%d\n", ft_printf("[%-07.9u]\n", 256));
	printf("-------\n");
	printf("%d\n", printf("[%02.1u]\n", 235));
	printf("%d\n", ft_printf("[%02.1u]\n", 235));
	printf("-------\n");
	printf("%d\n", printf("[%010.u]\n", -235));
	printf("%d\n", ft_printf("[%010.u]\n", -235));
	printf("-------\n");
	printf("%d\n", printf("[%010.*u]\n", -4, 235));
	printf("%d\n", ft_printf("[%010.*u]\n", -4, 235));
	printf("-------\n");
	printf("%d\n", printf("[%*.9u]\n", -7, 23));
	printf("%d\n", ft_printf("[%*.9u]\n", -7, 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.*u]\n", -9, 23));
	printf("%d\n", ft_printf("[%7.*u]\n", -9, 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.*u]\n", 0, 23));
	printf("%d\n", ft_printf("[%7.*u]\n", 0, 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.u]\n", 23));
	printf("%d\n", ft_printf("[%7.u]\n", 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.0u]\n", 23));
	printf("%d\n", ft_printf("[%7.0u]\n", 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.-0u]\n", 23));
	printf("%d\n", ft_printf("[%7.-0u]\n", 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.*u]\n", -0, 23));
	printf("%d\n", ft_printf("[%7.*u]\n", -0, 23));
	printf("-------\n");
	printf("%d\n", printf("[%07.*u]\n", -9, 0));
	printf("%d\n", ft_printf("[%07.*u]\n", -9, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*u]\n", 0, 0));
	printf("%d\n", ft_printf("[%07.*u]\n", 0, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*u]\n", -0, 0));
	printf("%d\n", ft_printf("[%07.*u]\n", -0, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.u]\n", 0));
	printf("%d\n", ft_printf("[%07.u]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.0u]\n", 0));
	printf("%d\n", ft_printf("[%07.0u]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.-0u]\n", 0));
	printf("%d\n", ft_printf("[%07.-0u]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*u]\n", -9, 0));
	printf("%d\n", ft_printf("[%07.*u]\n", -9, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*u]\n", 0, 0));
	printf("%d\n", ft_printf("[%07.*u]\n", 0, 0));
	printf("-------\n");
	printf("%d\n", printf("[min%04.*uint]\n", 20, 4294967295));
	printf("%d\n", ft_printf("[min%04.*uint]\n", 20, 4294967295));
	printf("-------\n");
	printf("%d\n", printf("[min%04.*uint]\n", 20, -4294967295));
	printf("%d\n", ft_printf("[min%04.*uint]\n", 20, -4294967295));
	printf("-------\n");
	printf("%d\n", printf("[max%-04.*uint]\n", -20, 4294967296));
	printf("%d\n", ft_printf("[max%-04.*uint]\n", -20, 4294967296));
	printf("-------\n");
	printf("%d\n", printf("[aa%04ubb]\n", -42));
	printf("%d\n", ft_printf("[aa%04ubb]\n", -42));
	printf("-------\n");
	printf("%d\n", printf("[%007u]\n", -21));
	printf("%d\n", ft_printf("[%007u]\n", -21));
	printf("-------\n");
	printf("%d\n", printf("[%0000--8u]\n", -21));
	printf("%d\n", ft_printf("[%0000--8u]\n", -21));
	printf("-------\n");
	printf("%d\n", printf("[%---6.5u]\n", 21));
	printf("%d\n", ft_printf("[%---6.5u]\n", 21));
	printf("-------\n");
	printf("%d\n", printf("[%---6.7u]\n", -21));
	printf("%d\n", ft_printf("[%---6.7u]\n", -21));
	printf("       \n");

	printf("UNDEFINED U\n");
	printf("%d\n", printf("[%7.-1u]\n", -92));
	printf("%d\n", ft_printf("[%7.-1u]\n", -92));
	printf("-------\n");
	printf("%d\n", printf("[%7.-6u]\n", -92));
	printf("%d\n", ft_printf("[%7.-6u]\n", -92));
	printf("-------\n");
	printf("%d\n", printf("[%7.-8u]\n", 0));
	printf("%d\n", ft_printf("[%7.-8u]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%10.-8u]\n", 9));
	printf("%d\n", ft_printf("[%10.-8u]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%10.-8u]\n", 0));
	printf("%d\n", ft_printf("[%10.-8u]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.-8u]\n", 9));
	printf("%d\n", ft_printf("[%07.-8u]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%07.-8u]\n", -240));
	printf("%d\n", ft_printf("[%07.-8u]\n", -240));
	printf("-------\n");
	printf("%d\n", printf("[%07.-8u]\n", 0));
	printf("%d\n", ft_printf("[%07.-8u]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%010.-8u]\n", 9));
	printf("%d\n", ft_printf("[%010.-8u]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%010.-8u]\n", -0));
	printf("%d\n", ft_printf("[%010.-8u]\n", -0));
	printf("-------\n");
	printf("%d\n", printf("[%-07.-8u]\n", 9));
	printf("%d\n", ft_printf("[%-07.-8u]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%-07.-8u]\n", 0));
	printf("%d\n", ft_printf("[%-07.-8u]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-8u]\n", 9));
	printf("%d\n", ft_printf("[%-010.-8u]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-0u]\n", 9));
	printf("%d\n", ft_printf("[%-010.-0u]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-8u]\n", 0));
	printf("%d\n", ft_printf("[%-010.-8u]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-0u]\n", 0));
	printf("%d\n", ft_printf("[%-010.-0u]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-u]\n", 9));
	printf("%d\n", ft_printf("[%-010.-u]\n", 9));
	printf("       \n");

	printf("NORMAL xX\n");
	printf("%d\n", printf("[%9.7x]\n", 23));
	printf("%d\n", ft_printf("[%9.7x]\n", 23));
	printf("-------\n");
	printf("%d\n", printf("[%09.7x]\n", 21));
	printf("%d\n", ft_printf("[%09.7x]\n", 21));
	printf("-------\n");
	printf("%d\n", printf("[%7.9X]\n", 21));
	printf("%d\n", ft_printf("[%7.9X]\n", 21));
	printf("-------\n");
	printf("%d\n", printf("[%07.9X]\n", -56));
	printf("%d\n", ft_printf("[%07.9X]\n", -56));
	printf("-------\n");
	printf("%d\n", printf("[%-7.9x]\n", 3578));
	printf("%d\n", ft_printf("[%-7.9x]\n", 3578));
	printf("-------\n");
	printf("%d\n", printf("[%-07.9x]\n", 256));
	printf("%d\n", ft_printf("[%-07.9x]\n", 256));
	printf("-------\n");
	printf("%d\n", printf("[%02.1x]\n", 235));
	printf("%d\n", ft_printf("[%02.1x]\n", 235));
	printf("-------\n");
	printf("%d\n", printf("[%010.x]\n", -235));
	printf("%d\n", ft_printf("[%010.x]\n", -235));
	printf("-------\n");
	printf("%d\n", printf("[%010.*x]\n", -4, 235));
	printf("%d\n", ft_printf("[%010.*x]\n", -4, 235));
	printf("-------\n");
	printf("%d\n", printf("[%*.9x]\n", -7, 23));
	printf("%d\n", ft_printf("[%*.9x]\n", -7, 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.*x]\n", -9, 23));
	printf("%d\n", ft_printf("[%7.*x]\n", -9, 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.*x]\n", 0, 23));
	printf("%d\n", ft_printf("[%7.*x]\n", 0, 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.x]\n", 23));
	printf("%d\n", ft_printf("[%7.x]\n", 23));
	printf("-------\n");
	printf("%d\n", printf("[%7.0X]\n", 23));
	printf("%d\n", ft_printf("[%7.0X]\n", 23));
	printf("-------\n");
	printf("%d\n", printf("[%07.-0X]\n", 23));
	printf("%d\n", ft_printf("[%07.-0X]\n", 23));
	printf("-------\n");
	printf("%d\n", printf("[%*.*X]\n", -7, -0, 23));
	printf("%d\n", ft_printf("[%*.*X]\n", -7, -0, 23));
	printf("-------\n");
	printf("%d\n", printf("[%07.*x]\n", -9, 0));
	printf("%d\n", ft_printf("[%07.*x]\n", -9, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*x]\n", 0, 0));
	printf("%d\n", ft_printf("[%07.*x]\n", 0, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*x]\n", -0, 0));
	printf("%d\n", ft_printf("[%07.*x]\n", -0, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.x]\n", 0));
	printf("%d\n", ft_printf("[%07.x]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.0X]\n", 0));
	printf("%d\n", ft_printf("[%07.0X]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.-0X]\n", 0));
	printf("%d\n", ft_printf("[%07.-0X]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*X]\n", -9, 0));
	printf("%d\n", ft_printf("[%07.*X]\n", -9, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*x]\n", 0, 0));
	printf("%d\n", ft_printf("[%07.*x]\n", 0, 0));
	printf("-------\n");
	printf("%d\n", printf("[min%04.*xint]\n", 20, -2147483648));
	printf("%d\n", ft_printf("[min%04.*xint]\n", 20, -2147483648));
	printf("-------\n");
	printf("%d\n", printf("[min%04.*xxint]\n", 20, -2147483650));
	printf("%d\n", ft_printf("[min%04.*xxint]\n", 20, -2147483650));
	printf("-------\n");
	printf("%d\n", printf("[max%-04.*xXint]\n", -20, 2147483647));
	printf("%d\n", ft_printf("[max%-04.*xXint]\n", -20, 2147483647));
	printf("-------\n");
	printf("%d\n", printf("[max%-04.*xint]\n", -20, 2147483650));
	printf("%d\n", ft_printf("[max%-04.*xint]\n", -20, 2147483650));
	printf("-------\n");
	printf("%d\n", printf("[aa%04xbb]\n", -42));
	printf("%d\n", ft_printf("[aa%04xbb]\n", -42));
	printf("-------\n");
	printf("%d\n", printf("[%007x]\n", -21));
	printf("%d\n", ft_printf("[%007x]\n", -21));
	printf("-------\n");
	printf("%d\n", printf("[%0000--8x]\n", -21));
	printf("%d\n", ft_printf("[%0000--8x]\n", -21));
	printf("-------\n");
	printf("%d\n", printf("[%---6.5x]\n", 21));
	printf("%d\n", ft_printf("[%---6.5x]\n", 21));
	printf("-------\n");
	printf("%d\n", printf("[%---6.7x]\n", -21));
	printf("%d\n", ft_printf("[%---6.7x]\n", -21));
	printf("       \n");

	printf("UNDEFINED xX\n");
	printf("%d\n", printf("[%7.-1x]\n", -92));
	printf("%d\n", ft_printf("[%7.-1x]\n", -92));
	printf("-------\n");
	printf("%d\n", printf("[%7.-6x]\n", -92));
	printf("%d\n", ft_printf("[%7.-6x]\n", -92));
	printf("-------\n");
	printf("%d\n", printf("[%7.-8x]\n", 0));
	printf("%d\n", ft_printf("[%7.-8x]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%10.-8x]\n", 9));
	printf("%d\n", ft_printf("[%10.-8x]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%10.-8d]\n", 0));
	printf("%d\n", ft_printf("[%10.-8d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.-8d]\n", 9));
	printf("%d\n", ft_printf("[%07.-8d]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%07.-8d]\n", -240));
	printf("%d\n", ft_printf("[%07.-8d]\n", -240));
	printf("-------\n");
	printf("%d\n", printf("[%07.-8d]\n", 0));
	printf("%d\n", ft_printf("[%07.-8d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%010.-8x]\n", 9));
	printf("%d\n", ft_printf("[%010.-8x]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%010.-8x]\n", -0));
	printf("%d\n", ft_printf("[%010.-8x]\n", -0));
	printf("-------\n");
	printf("%d\n", printf("[%-07.-8x]\n", 9));
	printf("%d\n", ft_printf("[%-07.-8x]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%-07.-8x]\n", 0));
	printf("%d\n", ft_printf("[%-07.-8x]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-8x]\n", 16));
	printf("%d\n", ft_printf("[%-010.-8x]\n", 16));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-0x]\n", 240));
	printf("%d\n", ft_printf("[%-010.-0x]\n", 240));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-8x]\n", -300));
	printf("%d\n", ft_printf("[%-010.-8x]\n", -300));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-0x]\n", 0));
	printf("%d\n", ft_printf("[%-010.-0x]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-x]\n", 42));
	printf("%d\n", ft_printf("[%-010.-x]\n", 42));
	printf("       \n");
*/

	printf("NORMAL s\n");
	printf("%d\n", printf("[%42s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%42s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%11s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%11s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%1s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%1s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%-42s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%-42s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%-11s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%-11s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%-1s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%-1s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%042s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%042s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%011s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%011s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%01s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%01s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%-01s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%-01s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%.21s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%.21s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%.s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%.s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%.4s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%.4s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%.11s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%.11s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%*s]\n", 21, "Jabberwocky"));
	printf("%d\n", ft_printf("[%*s]\n", 21, "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%*s]\n", -9, "Jabberwocky"));
	printf("%d\n", ft_printf("[%*s]\n", -9, "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%.*s]\n", -0, "Jabberwocky"));
	printf("%d\n", ft_printf("[%.*s]\n", -0, "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%.*s]\n", 4, "Jabberwocky"));
	printf("%d\n", ft_printf("[%.*s]\n", 4, "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%.*s]\n", -4, "Jabberwocky"));
	printf("%d\n", ft_printf("[%.*s]\n", -4, "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%.*s]\n", -0, "Jabberwocky"));
	printf("%d\n", ft_printf("[%.*s]\n", -0, "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%-*.*s]\n", 11, 5, "Jabberwocky"));
	printf("%d\n", ft_printf("[%-*.*s]\n", 11, 5, "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%-0*.*s]\n", 1, -5, "Jabberwocky"));
	printf("%d\n", ft_printf("[%-0*.*s]\n", 1, -5, "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%0*.*s]\n", -7, 5, "Jabberwocky"));
	printf("%d\n", ft_printf("[%0*.*s]\n", -7, 5, "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%.-6s]\n", "Jabberwocky"));
	printf("%d\n", ft_printf("[%.-6s]\n", "Jabberwocky"));
	printf("-------\n");
	printf("%d\n", printf("[%7.-0s]\n", "hello"));
	printf("%d\n", ft_printf("[%7.-0s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%-07.2s]\n", "hello"));
	printf("%d\n", ft_printf("[%-07.2s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%-9.7s]\n", "hello"));
	printf("%d\n", ft_printf("[%-9.7s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%09.4s]\n", "hello"));
	printf("%d\n", ft_printf("[%09.4s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%7.3s]\n", "hello"));
	printf("%d\n", ft_printf("[%7.3s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%07.0s]\n", "hello"));
	printf("%d\n", ft_printf("[%07.0s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%07.s]\n", "hello"));
	printf("%d\n", ft_printf("[%07.s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%07.*s]\n", 0, "hello"));
	printf("%d\n", ft_printf("[%07.*s]\n", 0, "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%-07.*s]\n", -0, "hello"));
	printf("%d\n", ft_printf("[%-07.*s]\n", -0, "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%07.*s]\n", -3, "hello"));
	printf("%d\n", ft_printf("[%07.*s]\n", -3, "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%07.0s]\n", "hello"));
	printf("%d\n", ft_printf("[%07.0s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%7.-0s]\n", "hello"));
	printf("%d\n", ft_printf("[%7.-0s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%-7.1s]\n", "hello"));
	printf("%d\n", ft_printf("[%-7.1s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%-07.4s]\n", "hello"));
	printf("%d\n", ft_printf("[%-07.4s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%02.1s]\n", "hello"));
	printf("%d\n", ft_printf("[%02.1s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%010.s]\n", "hello"));
	printf("%d\n", ft_printf("[%010.s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%010.*s]\n", -4, "hello"));
	printf("%d\n", ft_printf("[%010.*s]\n", -4, "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%*.9s]\n", -7, "hello"));
	printf("%d\n", ft_printf("[%*.9s]\n", -7, "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%7.*s]\n", -9, "hello"));
	printf("%d\n", ft_printf("[%7.*s]\n", -9, "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%7.*s]\n", 0, "hello"));
	printf("%d\n", ft_printf("[%7.*s]\n", 0, "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%7.s]\n", "hello"));
	printf("%d\n", ft_printf("[%7.s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%7.0s]\n", "hello"));
	printf("%d\n", ft_printf("[%7.0s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%07.-0s]\n", "hello"));
	printf("%d\n", ft_printf("[%07.-0s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%7.*s]\n", -0, "hello"));
	printf("%d\n", ft_printf("[%7.*s]\n", -0, "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%7.-3s]\n", "hello"));
	printf("%d\n", ft_printf("[%7.-3s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%-07.-3s]\n", "hello"));
	printf("%d\n", ft_printf("[%-07.-3s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%07.-3s]\n", "hello"));
	printf("%d\n", ft_printf("[%07.-3s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%07.-0s]\n", "hello"));
	printf("%d\n", ft_printf("[%07.-0s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%07.-s]\n", "hello"));
	printf("%d\n", ft_printf("[%07.-s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%07.*s]\n", -3, "hello"));
	printf("%d\n", ft_printf("[%07.*s]\n", -3, "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%07.*s]\n", -0, "hello"));
	printf("%d\n", ft_printf("[%07.*s]\n", -0, "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%7.*s]\n", -10, "hello"));
	printf("%d\n", ft_printf("[%7.*s]\n", -10, "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%07.s]\n", "hello"));
	printf("%d\n", ft_printf("[%07.s]\n", "hello"));
	printf("-------\n");
	printf("%d\n", printf("[%7.-3s]\n", "\0"));
	printf("%d\n", ft_printf("[%7.-3s]\n", "\0"));
	printf("-------\n");
	printf("%d\n", printf("[%-07.-3s]\n", "\0"));
	printf("%d\n", ft_printf("[%-07.-3s]\n", "\0"));
	printf("-------\n");
	printf("%d\n", printf("[%07.-0s]\n", "\0"));
	printf("%d\n", ft_printf("[%07.-0s]\n", "\0"));
	printf("-------\n");
	printf("%d\n", printf("[%07.-s]\n", "\0"));
	printf("%d\n", ft_printf("[%07.-s]\n", "\0"));
	printf("-------\n");
	printf("%d\n", printf("[%07.*s]\n", -3, "\0"));
	printf("%d\n", ft_printf("[%07.*s]\n", -3, "\0"));
	printf("-------\n");
	printf("%d\n", printf("[%07.*s]\n", -0, "\0"));
	printf("%d\n", ft_printf("[%07.*s]\n", -0, "\0"));
	printf("-------\n");
	printf("%d\n", printf("[%7.*s]\n", -10, "\0"));
	printf("%d\n", ft_printf("[%7.*s]\n", -10, "\0"));
	printf("-------\n");
	printf("%d\n", printf("[%07.s]\n", "\0"));
	printf("%d\n", ft_printf("[%07.s]\n", "\0"));
	printf("-------\n");
	printf("%d\n", printf("[%07.0s]\n", "\0"));
	printf("%d\n", ft_printf("[%07.0s]\n", "\0"));
	printf("-------\n");
	printf("%d\n", printf("[%07.-0s]\n", NULL));
	printf("%d\n", ft_printf("[%07.-0s]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%07.-2s]\n", NULL));
	printf("%d\n", ft_printf("[%07.-2s]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%07.s]\n", NULL));
	printf("%d\n", ft_printf("[%07.s]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%07.0s]\n", NULL));
	printf("%d\n", ft_printf("[%07.0s]\n", NULL));
	printf("-------\n");
	printf("%d\n", printf("[%07.*s]\n", -1, NULL));
	printf("%d\n", ft_printf("[%07.*s]\n", -1, NULL));
	printf("-------\n");
	printf("%d\n", printf("[%020.*s]\n", 10, NULL));
	printf("%d\n", ft_printf("[%020.*s]\n", 10, NULL));
	printf("-------\n");

/*
	printf("%d\n", printf("[%07.*x]\n", -9, 0));
	printf("%d\n", ft_printf("[%07.*x]\n", -9, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*x]\n", 0, 0));
	printf("%d\n", ft_printf("[%07.*x]\n", 0, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*x]\n", -0, 0));
	printf("%d\n", ft_printf("[%07.*x]\n", -0, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.x]\n", 0));
	printf("%d\n", ft_printf("[%07.x]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.0X]\n", 0));
	printf("%d\n", ft_printf("[%07.0X]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.-0X]\n", 0));
	printf("%d\n", ft_printf("[%07.-0X]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*X]\n", -9, 0));
	printf("%d\n", ft_printf("[%07.*X]\n", -9, 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.*x]\n", 0, 0));
	printf("%d\n", ft_printf("[%07.*x]\n", 0, 0));
	printf("-------\n");
	printf("%d\n", printf("[min%04.*xint]\n", 20, -2147483648));
	printf("%d\n", ft_printf("[min%04.*xint]\n", 20, -2147483648));
	printf("-------\n");
	printf("%d\n", printf("[min%04.*xxint]\n", 20, -2147483650));
	printf("%d\n", ft_printf("[min%04.*xxint]\n", 20, -2147483650));
	printf("-------\n");
	printf("%d\n", printf("[max%-04.*xXint]\n", -20, 2147483647));
	printf("%d\n", ft_printf("[max%-04.*xXint]\n", -20, 2147483647));
	printf("-------\n");
	printf("%d\n", printf("[max%-04.*xint]\n", -20, 2147483650));
	printf("%d\n", ft_printf("[max%-04.*xint]\n", -20, 2147483650));
	printf("-------\n");
	printf("%d\n", printf("[aa%04xbb]\n", -42));
	printf("%d\n", ft_printf("[aa%04xbb]\n", -42));
	printf("-------\n");
	printf("%d\n", printf("[%007x]\n", -21));
	printf("%d\n", ft_printf("[%007x]\n", -21));
	printf("-------\n");
	printf("%d\n", printf("[%0000--8x]\n", -21));
	printf("%d\n", ft_printf("[%0000--8x]\n", -21));
	printf("-------\n");
	printf("%d\n", printf("[%---6.5x]\n", 21));
	printf("%d\n", ft_printf("[%---6.5x]\n", 21));
	printf("-------\n");
	printf("%d\n", printf("[%---6.7x]\n", -21));
	printf("%d\n", ft_printf("[%---6.7x]\n", -21));
	printf("       \n");

	printf("UNDEFINED xX\n");
	printf("%d\n", printf("[%7.-1x]\n", -92));
	printf("%d\n", ft_printf("[%7.-1x]\n", -92));
	printf("-------\n");
	printf("%d\n", printf("[%7.-6x]\n", -92));
	printf("%d\n", ft_printf("[%7.-6x]\n", -92));
	printf("-------\n");
	printf("%d\n", printf("[%7.-8x]\n", 0));
	printf("%d\n", ft_printf("[%7.-8x]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%10.-8x]\n", 9));
	printf("%d\n", ft_printf("[%10.-8x]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%10.-8d]\n", 0));
	printf("%d\n", ft_printf("[%10.-8d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%07.-8d]\n", 9));
	printf("%d\n", ft_printf("[%07.-8d]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%07.-8d]\n", -240));
	printf("%d\n", ft_printf("[%07.-8d]\n", -240));
	printf("-------\n");
	printf("%d\n", printf("[%07.-8d]\n", 0));
	printf("%d\n", ft_printf("[%07.-8d]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%010.-8x]\n", 9));
	printf("%d\n", ft_printf("[%010.-8x]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%010.-8x]\n", -0));
	printf("%d\n", ft_printf("[%010.-8x]\n", -0));
	printf("-------\n");
	printf("%d\n", printf("[%-07.-8x]\n", 9));
	printf("%d\n", ft_printf("[%-07.-8x]\n", 9));
	printf("-------\n");
	printf("%d\n", printf("[%-07.-8x]\n", 0));
	printf("%d\n", ft_printf("[%-07.-8x]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-8x]\n", 16));
	printf("%d\n", ft_printf("[%-010.-8x]\n", 16));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-0x]\n", 240));
	printf("%d\n", ft_printf("[%-010.-0x]\n", 240));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-8x]\n", -300));
	printf("%d\n", ft_printf("[%-010.-8x]\n", -300));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-0x]\n", 0));
	printf("%d\n", ft_printf("[%-010.-0x]\n", 0));
	printf("-------\n");
	printf("%d\n", printf("[%-010.-x]\n", 42));
	printf("%d\n", ft_printf("[%-010.-x]\n", 42));
	printf("       \n");
*/

	printf("%d\n", ft_printf("[%07.s]\n", "hello"));
	printf("%d\n", ft_printf("[%07.0s]\n", "hello"));

	return (0);
}